### ISSUE TITLE
Nginx installation error

### ISSUE THREAD

**Issue by artmouse** [magenx/Magento-2-server-installation#1]
By default installing nginx v1.14
please add:
`--disablerepo=rhel-8-for-x86_64-appstream-rpms`
to install nginx script

**Comment by magenx** [comment]
i see nginx  1.17.9

**Comment by magenx** [comment]
```
[root@magento-2 ~]# dnf repolist
DigitalOcean Agent                                                                                                                           65 kB/s | 3.3 kB     00:00    
repo id                                                          repo name                                                                                            status
AppStream                                                        CentOS-8 - AppStream                                                                                 5,071
BaseOS                                                           CentOS-8 - Base                                                                                      2,126
PowerTools                                                       CentOS-8 - PowerTools                                                                                1,525
digitalocean-agent                                               DigitalOcean Agent                                                                                      17
*epel                                                            Extra Packages for Enterprise Linux 8 - x86_64                                                       5,127
*epel-modular                                                    Extra Packages for Enterprise Linux Modular 8 - x86_64                                                   0
extras                                                           CentOS-8 - Extras                                                                                       12
nginx-mainline                                                   nginx mainline repo                                                                                    112
percona-release-noarch                                           Percona Original release/noarch YUM repository                                                           6
percona-release-x86_64                                           Percona Original release/x86_64 YUM repository                                                         239
proxysql_repo                                                    ProxySQL YUM repository                                                                                  3
remi                                                             Remi's RPM repository for Enterprise Linux 8 - x86_64                                                3,656
remi-modular                                                     Remi's Modular repository for Enterprise Linux 8 - x86_64                                              371
remi-safe                                                        Safe Remi's RPM repository for Enterprise Linux 8 - x86_64                                           2,140
tools-release-noarch                                             Percona Tools release/noarch YUM repository                                                              0
tools-release-x86_64                                             Percona Tools release/x86_64 YUM repository                                                             95
```
```
[root@magento-2 ~]# dnf module list --disabled
Last metadata expiration check: 0:01:18 ago on Fri 03 Apr 2020 06:01:19 PM UTC.
CentOS-8 - AppStream
Name                                Stream                                     Profiles                                         Summary                                     
mysql                               8.0 [d][x]                                 client, server [d]                               MySQL Module                                
nginx                               1.14 [d][x]                                common [d]                                       nginx webserver                             
nginx                               1.16 [x]                                   common                                           nginx webserver                             

Extra Packages for Enterprise Linux Modular 8 - x86_64
Name                                Stream                                     Profiles                                         Summary                                     
nginx                               mainline [x]                               common                                           nginx webserver                             

Hint: [d]efault, [e]nabled, [x]disabled, [i]nstalled
```

**Comment by artmouse** [comment]
Setup with error:

> package nginx-module-perl-1:1.17.9-1.el8.ngx.x86_64 requires nginx = 1:1.17.9-1.el8.ngx, but none of the providers can be installed

**Comment by artmouse** [comment]
`dnf repolist
Last metadata expiration check: 0:27:10 ago on Sat 04 Apr 2020 08:54:34 AM CEST.
repo id                                                                             repo name                                                                                                           status
AppStream                                                                           CentOS-8 - AppStream                                                                                                5,079
BaseOS                                                                              CentOS-8 - Base                                                                                                     2,126
PowerTools                                                                          CentOS-8 - PowerTools                                                                                               1,525
*epel                                                                               Extra Packages for Enterprise Linux 8 - x86_64                                                                      5,137
*epel-modular                                                                       Extra Packages for Enterprise Linux Modular 8 - x86_64                                                                  0
extras                                                                              CentOS-8 - Extras                                                                                                      12
getpagespeed-extras                                                                 GetPageSpeed packages for Enterprise Linux 8 - x86_64                                                               1,128
getpagespeed-extras-noarch                                                          GetPageSpeed packages for Enterprise Linux 8 - noarch                                                                 157
nginx-mainline                                                                      nginx mainline repo                                                                                                   112
percona-release-noarch                                                              Percona Original release/noarch YUM repository                                                                          6
percona-release-x86_64                                                              Percona Original release/x86_64 YUM repository                                                                        239
proxysql_repo                                                                       ProxySQL YUM repository                                                                                                 3
remi                                                                                Remi's RPM repository for Enterprise Linux 8 - x86_64                                                               3,656
remi-modular                                                                        Remi's Modular repository for Enterprise Linux 8 - x86_64                                                             371
remi-safe                                                                           Safe Remi's RPM repository for Enterprise Linux 8 - x86_64                                                          2,145
tools-release-noarch                                                                Percona Tools release/noarch YUM repository                                                                             0
tools-release-x86_64                                                                Percona Tools release/x86_64 YUM repository  `

`dnf module list --disabled
Last metadata expiration check: 0:28:26 ago on Sat 04 Apr 2020 08:54:34 AM CEST.
CentOS-8 - AppStream
Name                                          Stream                                             Profiles                                                  Summary
mysql                                         8.0 [d][x]                                         client, server [d]                                        MySQL Module

Hint: [d]efault, [e]nabled, [x]disabled, [i]nstalled
`

**Comment by magenx** [comment]
i dont know why you have this:

```
getpagespeed-extras                                                                 GetPageSpeed packages for Enterprise Linux 8 - x86_64                                                               1,128
getpagespeed-extras-noarch                                                          GetPageSpeed packages for Enterprise Linux 8 - noarch                                                                 157
```

this is something not related to our stack.
