### ISSUE TITLE
Access remote site

### ISSUE THREAD

**Issue by teodorpav** [magenx/Magento-2-server-installation#10]
Hi,
server settings issue:

[root@server:~]$ wget https://uchmag.com
--2020-08-29 01:51:17--  https://uchmag.com/
Resolving uchmag.com (uchmag.com)... 94.155.47.111
Connecting to uchmag.com (uchmag.com)|94.155.47.111|:443... connected.
GnuTLS: The Diffie-Hellman prime sent by the server is not acceptable (not long enough).
Unable to establish SSL connection.

Can you check why?
I can access this from other servers and I can access others sites.

**Comment by magenx** [comment]
how exactly this related to Magento 2 server installation config?

**Comment by teodorpav** [comment]
On the clean Centos installation this works.
But yes it is not M2 connected (maybe some firewall settings from the script).

Thank you

**Comment by magenx** [comment]
https://www.ssllabs.com/ssltest/analyze.html?d=uchmag.com
