### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by gfxguru** [magenx/Magento-2-server-installation#100]
Class "Magento\AdminAdobeIms\Service\ImsConfig" does not exist
  Class Magento\TwoFactorAuth\Observer\ControllerActionPredispatch\Interceptor generation error: The requ
  ested class did not generate properly, because the 'generated' directory permission is read-only. If --
  - after running the 'bin/magento setup:di:compile' CLI command when the 'generated' directory permissio
  n is set to write --- the requested class did not generate properly, then you must add the generated cl
  ass object to the signature of the related construct method, only.

**Comment by corpsysgit** [comment]
Remove all Ims quotes from this file:
TwoFactorAuth/Observer/ControllerActionPredispatch.php 

should compile.

**Comment by gfxguru** [comment]
vendor/magento/module-two-factor-auth/Observer/ControllerActionPredispatch.php, Really?

Has anyone else come up with a solution or fix?

**Comment by corpsysgit** [comment]
Temporary solution. Removes quotes from the Ims class inside the file, managing to compile the code after that.

Want a definitive solution, wait for Adobe.

**Comment by gfxguru** [comment]
Remove quotes? you mean remove all code with ims? This file is loaded with references to ims

**Comment by gfxguru** [comment]
Duplicate issue
