### ISSUE TITLE
Restoring a Magento install

### ISSUE THREAD

**Issue by gfxguru** [magenx/Magento-2-server-installation#101]
Restoring a know good backup changed the directory access rights? What's funny is the directories seem to be assigned the correct magento user and php-magento group but still getting permission denied.

**Comment by artmouse** [comment]
sudo chown magento:php-magento folder_name

**Comment by gfxguru** [comment]
What I can't figure out is the folders seem to be assigned the correct access but I'm still getting Permission errors from nginx??

**Comment by artmouse** [comment]
> What I can't figure out is the folders seem to be assigned the correct access but I'm still getting Permission errors from nginx??

Check www.conf on /etc/php/PHP_VERSION/fpm/pool.d

![image](https://user-images.githubusercontent.com/527232/187417449-20fb745b-d358-43db-9512-b19c73c46cd1.png)

**Comment by artmouse** [comment]
When you run any command for magento cli or custom php script,
please use magento user, either switch to:
su magento -s /bin/bash

or run commands from root as user:
su magento -s /bin/bash -c 'bin/magento'

This also applies to working with files.

**Comment by gfxguru** [comment]
I use the magento user when I use the command line, and the listen.owner = magento, listen.group = php-group. within www.conf

**Comment by gfxguru** [comment]
what email address? never received. gfxguru@gmail.com

**Comment by gfxguru** [comment]
got it
