### ISSUE TITLE
503 Backend fetch failed

### ISSUE THREAD

**Issue by gfxguru** [magenx/Magento-2-server-installation#102]
I've had to restore Magento 2.4.4 from a zipped backup. Now I'm getting 503 Backend fetch failed. Nginx error is:

2022/08/28 11:42:31 [crit] 756#756: *2703 open() /pub/health_check.php" failed (13: Permission denied), client: 127.0.0.1, server: www.mydomain.com, request: "GET /health_check.php HTTP/1.1", host: "localhost"

I'm lost with this error and can't understand why client:127.0.0.1, varnish is getting permission denied. How do I check/set permissions for varnish?

**Comment by gfxguru** [comment]
Ok so I've disabled the probe on default.vcl and I'm getting Permission denied from nginx but the directories are assigned the magento user and the php group?

**Comment by artmouse** [comment]
> Ok so I've disabled the probe on default.vcl and I'm getting Permission denied from nginx but the directories are assigned the magento user and the php group?

I think with questions like this you'd better go stackoverflow...

**Comment by gfxguru** [comment]
Trust me I have
