### ISSUE TITLE
How do I configure for multi stores?

### ISSUE THREAD

**Issue by corpsysgit** [magenx/Magento-2-server-installation#105]
How do I configure for multi stores?

**Comment by artmouse** [comment]
> How do I configure for multi stores?

Configure domains and storecode in file /etc/nginx/conf_m2/maps.conf
https://github.com/magenx/Magento-nginx-config/blob/bb3a97d20f5e21ae2aa4b43c43780f0845d5f97c/magento2/conf_m2/maps.conf#L50

In /etc/nginx/sites-available/magento2.conf uncomment two line for each domains
https://github.com/magenx/Magento-nginx-config/blob/bb3a97d20f5e21ae2aa4b43c43780f0845d5f97c/magento2/sites-available/magento2.conf#L99

**Comment by magenx** [comment]
you need to enter your store/website code into nginx config

**Comment by corpsysgit** [comment]
Thank you guys! 

Do you know if I need to enable the option:

Add Store Code to Url's

![Captura de Tela 2022-10-01 às 16 54 00](https://user-images.githubusercontent.com/15632329/193426084-1654d6c6-e145-4507-ab9d-1e006e66f803.png)

**Comment by corpsysgit** [comment]
Thank you guys!

Do you know if I need to enable the option:

Add Store Code to Url's

![image](https://user-images.githubusercontent.com/15632329/193426287-e36bf1da-6685-400a-891e-180263ea88b0.png)

**Comment by corpsysgit** [comment]
Work. Thanks!
