### ISSUE TITLE
When we try to change a code, our change is not reflected

### ISSUE THREAD

**Issue by flaviub** [magenx/Magento-2-server-installation#106]
As we tried to debug and change a code but our change is not reflected also run all basic commands but still our changes are not reflected.

Can someoane help us?

**Comment by artmouse** [comment]
> As we tried to debug and change a code but our change is not reflected also run all basic commands but still our changes are not reflected.
> 
> Can someoane help us?

Try to restart php-fpm for clear opcache. And flush REDIS cache.

**Comment by magenx** [comment]
you can use [cacheflush](https://github.com/magenx/Magento-2-server-installation/blob/master/magenx.install.latest.sh#L1703)

make sure you have also varnish and redis properly configured in `env.php`

**Comment by flaviub** [comment]
Something sound to be wrong, the website is loading ok but if I want to restart the nginx I have this error:

systemctl restart nginx.service
Failed to restart nginx.service: Unit not found.

Also when I want to view the nginx status:

service nginx status
Redirecting to /bin/systemctl status nginx.service
Unit nginx.service could not be found.

Do you now why?
