### ISSUE TITLE
Error when run bin/magento setup:di:compile

### ISSUE THREAD

**Issue by flaviub** [magenx/Magento-2-server-installation#107]
Hello,

When we run this command bin/magento setup:di:compile we have this errors, can you help us?

php bin/magento setup:di:compile

Compilation was started.
Repositories code generation... 1/9 [===>------------------------]  11% < 1 sec 76.0 MiBsyntax error, unexpected token "(", expecting variable#0 /home/antares/public_html/vendor/composer/ClassLoader.php(428): Composer\Autoload\includeFile()
#1 [internal function]: Composer\Autoload\ClassLoader->loadClass()
#2 /home/antares/public_html/setup/src/Magento/Setup/Module/Di/Code/Reader/ClassesScanner.php(134): class_exists()
#3 /home/antares/public_html/setup/src/Magento/Setup/Module/Di/Code/Reader/ClassesScanner.php(117): Magento\Setup\Module\Di\Code\Reader\ClassesScanner->includeClass()
#4 /home/antares/public_html/setup/src/Magento/Setup/Module/Di/Code/Reader/ClassesScanner.php(87): Magento\Setup\Module\Di\Code\Reader\ClassesScanner->extract()
#5 /home/antares/public_html/setup/src/Magento/Setup/Module/Di/App/Task/Operation/RepositoryGenerator.php(61): Magento\Setup\Module\Di\Code\Reader\ClassesScanner->getList()
#6 /home/antares/public_html/setup/src/Magento/Setup/Module/Di/App/Task/Manager.php(56): Magento\Setup\Module\Di\App\Task\Operation\RepositoryGenerator->doOperation()
#7 /home/antares/public_html/setup/src/Magento/Setup/Console/Command/DiCompileCommand.php(216): Magento\Setup\Module\Di\App\Task\Manager->process()
#8 /home/antares/public_html/vendor/symfony/console/Command/Command.php(255): Magento\Setup\Console\Command\DiCompileCommand->execute()
#9 /home/antares/public_html/vendor/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run()
#10 /home/antares/public_html/vendor/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand()
#11 /home/antares/public_html/vendor/magento/framework/Console/Cli.php(115): Symfony\Component\Console\Application->doRun()
#12 /home/antares/public_html/vendor/symfony/console/Application.php(149): Magento\Framework\Console\Cli->doRun()
#13 /home/antares/public_html/bin/magento(23): Symfony\Component\Console\Application->run()
#14 {main}

**Comment by magenx** [comment]
hi
you have typo in your code:
`syntax error, unexpected token "(", expecting variable`

**Comment by flaviub** [comment]
Ok, can you tell me how can I find where is the problem?

In this file /public_html/vendor/composer/ClassLoader.php on line 428 we have this:

 includeFile($file);

This is a part of this function:

public function loadClass($class)
    {
        if ($file = $this->findFile($class)) {
            includeFile($file);

            return true;
        }

        return null;
    }

**Comment by corpsysgit** [comment]
try:

composer dump-autoload

and then:

composer update
bin/magento setup:upgrade
bin/magento setup:di:compile

**Comment by magenx** [comment]
there must be path to file in traces
Composer\Autoload\includeFile() -> .....
but i dont see it

try to run command with debug options like:
`php -d display_errors=1 bin/magento setup:di:compile -vvv`
