### ISSUE TITLE
Connection Refused Errors

### ISSUE THREAD

**Issue by joemstar** [magenx/Magento-2-server-installation#11]
I have tried running this setup on a new CentOS VPS with Digital Ocean 3 different times and have not had success. All installations are successful except for Let's Encrypt. I was able to run these command manually afterward with success. After reviewing the install output I noticed this error: Could not connect to Redis at 127.0.0.1:6380: Connection refused. Additionally, when I try to access my domain with my web browser I get a connection refused error on port 443. When I try to access the server on port 80, I receive this error from the Varnish Cache Server:

Error 503 Backend fetch failed
Backend fetch failed
Guru Meditation

Am I missing something basic? I have followed the instructions exactly.

**Comment by magenx** [comment]
this magento stack is easy to debug, 
usually some issues only related to correct request flow.

**Comment by JAG007** [comment]
> I have tried running this setup on a new CentOS VPS with Digital Ocean 3 different times and have not had success. All installations are successful except for Let's Encrypt. I was able to run these command manually afterward with success. After reviewing the install output I noticed this error: Could not connect to Redis at 127.0.0.1:6380: Connection refused. Additionally, when I try to access my domain with my web browser I get a connection refused error on port 443. When I try to access the server on port 80, I receive this error from the Varnish Cache Server:
> 
> Error 503 Backend fetch failed
> Backend fetch failed
> Guru Meditation
> 
> Am I missing something basic? I have followed the instructions exactly.

Any Luck in fixing the ERR_CONNECTION_REFUSED?
I am having the same issue.

Use this command to fix Backend Fetch failed
sed -i 's/.url =.*\/pub\/health_check\.php.*;/.url = "\/health_check\.php";/' /etc/varnish/default.vcl
or you can edit /etc/varnish/default.vcl manually. Change .url = "/pub/health_check.php";    to    .url = "/health_check.php";
