### ISSUE TITLE
How I can upgrade all magenx installed packages?

### ISSUE THREAD

**Issue by Veltix** [magenx/Magento-2-server-installation#115]
How I can upgrade all magenx installed packages and magento 2 version to latest?
I want use magenx latest configurations + update magento version to 2.4.5

**Comment by artmouse** [comment]
> How I can upgrade all magenx installed packages and magento 2 version to latest? I want use magenx latest configurations + update magento version to 2.4.5

Manually update server software and magento packages.

**Comment by magenx** [comment]
to upgrade ubuntu/debian linux:
`apt update && apt upgrade -y`

magento:
```
composer require-commerce magento/product-community-edition=2.4.5-p1 --no-update
composer update
bin/magento setup:upgrade
```

but of course you have to understand all dependencies and consequences.
custom theme and additional modules must support the latest version of magento and php8.1
