### ISSUE TITLE
Form has more than 1000 fields - phpMyAdmin

### ISSUE THREAD

**Issue by musabatas** [magenx/Magento-2-server-installation#119]
php.ini not configured for phpMyAdmin

`Warning: a form on this page has more than 1000 fields. On submission, some of the fields might be ignored, due to PHP's max_input_vars configuration.`

**Comment by magenx** [comment]
if you check:
`php -i | grep max_input_vars`
what you see?

**Comment by magenx** [comment]
yes , `zz-NAME-overrides.ini` file only available in `cli/conf.d/`
needs to be in `fpm/conf.d/` also
