### ISSUE TITLE
Cart gives 404 error and admin login page without styles

### ISSUE THREAD

**Issue by Veltix** [magenx/Magento-2-server-installation#123]
Add to Cart gives 404 error and admin login page shows without styles.

Seems to be nginx issue.

Also discovered it shows index.php in url..

**Comment by magenx** [comment]
do you have any custom changes in nginx config?

**Comment by Veltix** [comment]
No, all same. Like installation provided there.

**Comment by fvlasie** [comment]
Check your store URLs. It seems maybe http and https are incorrectly assigned.
