### ISSUE TITLE
importing images via API

### ISSUE THREAD

**Issue by Veltix** [magenx/Magento-2-server-installation#130]
Im importing images via API and then all images show 415. I have to manually update permission every time it imports new images. Is there any possible solution for that?

5W-40-5-Liter-2022_600x600_png.png?width=75&height=75&store=et_EE&image-type=thumbnail

If I remove params then it shows image:
5W-40-5-Liter-2022_600x600_png.png

**Comment by magenx** [comment]
yes, you need to make sure that you have correct default permissions in parent folders
default acl must be set.
usually all folders owned by magento user and its php user group
and nginx with read permissions

**Comment by Veltix** [comment]
i have correct permissions and added 777 to pub media.
but if new image is added it doesnt have 777 permission.
It has magento {MAGENTO_USER}:php-{MAGENTO_USER} permission like other files.

**Comment by magenx** [comment]
why you think it must be **777**???
i have no idea why your product images bigger than 200kb ...

**Comment by Veltix** [comment]
Product image is 800x800px and 91kb

**Comment by magenx** [comment]
make sure you have `var/tmp` folder in magento
