### ISSUE TITLE
nc: command not found

### ISSUE THREAD

**Issue by fvlasie** [magenx/Magento-2-server-installation#136]
Hello!

I am trying to use your server installation script. It all seems to work until I try to "Install Magento no sample data" Then I get the error: magenx.sh: line 1342: nc: command not found

I am using Rocky linux 8.7 and I am running the commands in order. I have successfully completed lemp, magento, and database

Is there documentation for using this script?

Thank you!

**Comment by magenx** [comment]
it looks like missing `nc` package
you can install it manually

`dnf install -y nc`

**Comment by fvlasie** [comment]
Thank you!
