### ISSUE TITLE
SSH blocked

### ISSUE THREAD

**Issue by fvlasie** [magenx/Magento-2-server-installation#137]
How can I allow access to SSH? firewalld seems to be masked so what firewall service is Magenx using?

 I am running Rocky Linux 8.7

Thank you!

**Comment by magenx** [comment]
you can install `csf firewall` from menu. firewalld must be removed during setup.
https://github.com/magenx/Magento-2-server-installation/blob/master/magenx.install.latest.sh#L326
make sure you dont have any other hardware firewalls from your servers provider.
by default all ports are open.

**Comment by fvlasie** [comment]
Rerunning the setup seems to have solved the issue. Thank you!
