### ISSUE TITLE
Can't install with bash

### ISSUE THREAD

**Issue by ilevennet** [magenx/Magento-2-server-installation#14]
When I try to install with the command in your docs there's an error:

[root@dev ~]# curl -o magenx.sh https://magenx.sh && bash magenx.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   138  100   138    0     0   2464      0 --:--:-- --:--:-- --:--:--  2464
magenx.sh: line 1: html: No such file or directory
magenx.sh: line 2: syntax error near unexpected token `<'
'agenx.sh: line 2: `<head><title>302 Found</title></head>

the path is broken

**Comment by magenx** [comment]
yes it must be `-Lo`
`curl -Lo`
