### ISSUE TITLE
Redis not running on port 6380

### ISSUE THREAD

**Issue by fvlasie** [magenx/Magento-2-server-installation#144]
```
  [~]    MAGENTO 2.4.5-p1 SETUP    [~]
  -------------------------------------------------------------------------------------


Connection to localhost (::1) 6379 port [tcp/redis] succeeded!
nc: connect to localhost (::1) port 6380 (tcp) failed: Connection refused
nc: connect to localhost (127.0.0.1) port 6380 (tcp) failed: Connection refused
    [!] SERVICE 6380 OFFLINE
```

In `etc/redi/redis.conf` port 6380 does not appear to be enabled.

**Comment by magenx** [comment]
there is a bug with systemd file
not properly tested across all systems

it will be fixed in new release

but you can see difference in:
`/usr/lib/systemd/system/redis.service`

copy we created in `/etc/systemd/system/redis@.service`
