### ISSUE TITLE
No SSL terminator for Varnish

### ISSUE THREAD

**Issue by fvlasie** [magenx/Magento-2-server-installation#149]
Hello,

I discovered that there is no SSL terminator configured for Varnish. Is this intentional?

Could you consider including Hitch and maybe certbot?

Thank you!

**Comment by magenx** [comment]
there is ssl configration and termination

you have to install ssl cert with `certbot`
uncomment ssl in nginx
/nginx.conf
/sites-available/magento2.conf
conf_m2/varnish_proxy.conf
