### ISSUE TITLE
Kibana and Filebeat 

### ISSUE THREAD

**Issue by gfxguru** [magenx/Magento-2-server-installation#150]
I'm looking at the configuration and could like to use Kibana and Filebeat for other logs or stats on the server. Can you give us any hints on configuring. Not able to reach default Kibana web port.

**Comment by magenx** [comment]
you need to check filebeat documentation
https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-reference-yml.html

provided config is good to start with.
