### ISSUE TITLE
MariaDB 10.5.17 causes RDBMS error

### ISSUE THREAD

**Issue by fvlasie** [magenx/Magento-2-server-installation#153]
When running `bin/magento setup:upgrade` the following error shows:

```
Current version of RDBMS is not supported. Used Version: 10.5.17-MariaDB. Supported versions: MySQL-8, MySQL-5.7, MariaDB-(10.2-10.4)
```
Magento is not officially compatible with MariaDB 10.5. :(

Maybe the script should be installing MariaDB 10.4?

**Comment by jorgb90** [comment]
It is compatible, but you have overwritten the MagenX change in app/etc/di.xml on line 1856 it should be:

<item name="MariaDB-(10.2-10.5)" xsi:type="string">^10\.[2-5]\.</item>

Then everything works as expected.

**Comment by magenx** [comment]
https://github.com/magenx/Magento-2-server-installation/issues/82

**Comment by fvlasie** [comment]
Aha! Yes, I did overwrite that file. I was restoring from another Magento installation. Thank you for the tip @jorgb90 and thank you for the reference @magenx !

(Maybe we should start an FAQ...:)
