### ISSUE TITLE
nginx crashed by segfault libperl.so

### ISSUE THREAD

**Issue by Veltix** [magenx/Magento-2-server-installation#159]
I had weird problem where nginx crashed and didnt restart by himself...

Looking errors and seems like libperl bug?

Error:
`Dec 14 22:05:13 server.domain.com kernel: nginx[3007876]: segfault at 24415 ip 00007fc1267185d3 sp 00007ffc28ec23d0 error 4 in libperl.so.5.30.0[7fc1266a0000+16>
Dec 14 22:05:13 server.domain.com kernel: Code: 48 89 43 10 48 83 c4 18 2b 5d 41 5c 41 5d 41 5e 41 5f c3 0f 1f 40 00 0f b6 7f 30 48 c1 e8 03 48 29 f8 48 89 c3 7>
Dec 14 22:05:16 server.domain.com systemd[1]: nginx.service: Main process exited, code=dumped, status=11/SEGV
Dec 14 22:05:16 server.domain.com systemd[1]: nginx.service: Failed with result 'core-dump'.
Dec 14 22:05:19 server.domain.com systemd[1]: snap.certbot.renew.service: Succeeded.
Dec 14 22:05:19 server.domain.com systemd[1]: Finished Service for snap application certbot.renew.`

------------

Seems like in perl 5.30.0 this was common issue..

**Comment by magenx** [comment]
is it related to `snap.certbot.renew.service` timer
it sends some command to nginx?

**Comment by Veltix** [comment]
But why it crashes like that? If it renews new cert it would be nice it restarts by himself. I think I have same issue been before but didnt know really what caused it. I thought mysql eating RAM too much and nginx crashes. 

Is it normal 32GB RAM server and mariadb using 40-60% of memory?
"top" command shows:
MiB Mem :  31356.3 total,   2362.8 free,  15731.8 used,  13261.8 buff/cache
MiB Swap:      0.0 total,      0.0 free,      0.0 used.  14873.8 avail Mem 

MariaDB is one time crashed of memory. Thats weird because there is always alot avail Mem.

**Comment by magenx** [comment]
nginx reports bug in perl 5.30
needs upgrade to >5.32
