### ISSUE TITLE
Failed to start ProFTPD FTP Server

### ISSUE THREAD

**Issue by Stuart-Winterburn** [magenx/Magento-2-Server-Installation#161]
Message log shows:

fatal: HideNoAccess: directive not allowed in <Limit> context on line 122 of '/etc/proftpd.conf'

I have checked this area of the proftpd.conf

<Directory /home/*>
    HideFiles (\..*)$
    <Limit ALL>
        HideNoAccess on
        IgnoreHidden on
    </Limit>
</Directory>

I can't seem to see any issue with the code, commenting out "HideNoAccess on" does then allow ProFTPD to start but not sure if this is the best fix.

**Comment by magenx** [comment]
fix.

```
<Directory /home/*>
    HideNoAccess on
    HideFiles (\..*)$
    <Limit ALL>
        IgnoreHidden on
    </Limit>
</Directory>
```

**Comment by Stuart-Winterburn** [comment]
Perfect
