### ISSUE TITLE
/bin/bash: /usr/local/bin/cron_check.sh: No such file or directory

### ISSUE THREAD

**Issue by Stuart-Winterburn** [magenx/Magento-2-Server-Installation#162]
Receiving an email every 5 minutes:

/bin/bash: /usr/local/bin/cron_check.sh: No such file or directory

I believe it's related to commit: bd9d37be79e65273968c352ae0629f05e2052923

**Comment by magenx** [comment]
this is fixed now in installation script,
please remove cronjob for this file
