### ISSUE TITLE
php 8.1 socket disappears every day..

### ISSUE THREAD

**Issue by Veltix** [magenx/Magento-2-server-installation#163]
[error] 1392879#1392879: *1958 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: IP, server: domain.com, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/var/run/magento.sock:", host: "domain.com"

**Comment by magenx** [comment]
is there any other errors?
like php error or php-fpm error in syslog
