### ISSUE TITLE
Letsencrypt fails to validate as nginx blocks validation url

### ISSUE THREAD

**Issue by Stuart-Winterburn** [magenx/Magento-2-Server-Installation#163]
On fresh installation letsencrypt fails to validate as nginx is blocking the validation url, i added this to the nginx magento2.conf to get it to work:

location ^~ /.well-known/acme-challenge/ {
}

**Comment by Vinsar** [comment]
Location of magento2.conf ?

**Comment by mrlerch** [comment]
/etc/nginx/sites-available/magento2.conf
