### ISSUE TITLE
Kibana failes to install due to url errors

### ISSUE THREAD

**Issue by Stuart-Winterburn** [magenx/Magento-2-Server-Installation#164]
INSTALLATION OF KIBANA:
Attempting to transfer from https://packages.wazuh.com/wazuhapp/wazuhapp.zip
Attempting to transfer from https://artifacts.elastic.co/downloads/kibana-plugins/https://packages.wazuh.com/wazuhapp/wazuhapp.zip/https://packages.wazuh.com/wazuhapp/wazuhapp.zip-6.5.3.zip
Plugin installation was unsuccessful due to error "No valid url specified."

**Comment by magenx** [comment]
you can try to reinstall plugin with:
`/usr/share/kibana/bin/kibana-plugin install https://packages.wazuh.com/wazuhapp/wazuhapp-3.7.2_6.5.4.zip`

**Comment by Stuart-Winterburn** [comment]
Thanks, I will have a go with the link provided.

Kind Regards
Stuart
