### ISSUE TITLE
Checksum Error

### ISSUE THREAD

**Issue by zreon** [magenx/Magento-2-Server-Installation#165]
I'm receiving the following error on a fresh CentOS 7.0 minimal install.

` [UnexpectedValueException]
  The checksum verification of the file failed (downloaded from https://repo.magento.com/archives/vertex/module-tax/vertex-module-tax-3.0.0.0.zip)`

**Comment by magenx** [comment]
magento bug:
https://github.com/magento/magento2/issues/19934
