### ISSUE TITLE
Migrate data from other Magento install

### ISSUE THREAD

**Issue by fvlasie** [magenx/Magento-2-server-installation#165]
Merry Christmas!

I am trying to migrate from another installation (not Magenx script). I have replaced the migrated `app/etc/di.xml` to make it work with mariadb 10.5.
But now I am getting an error about elasticsearch: `Could not validate a connection to Elasticsearch. Unknown 401 error from Elasticsearch null`

I know it is because the elasticsearch settings are different in the DB imported from the other Magento. My question is: where can I find the elasticsearch setting used during setup?

I should be able to fix this issue with the following commands:
```
bin/magento config:set catalog/search/engine elasticsearch7
bin/magento config:set catalog/search/elasticsearch7_server_hostname <elasticsearch_hostname>
bin/magento config:set catalog/search/elasticsearch7_server_port <elasticsearch_port>
```
I think I will contribute a wiki page for migration once all the steps are figured out!

Thank you!

**Comment by magenx** [comment]
you have all files in:
`/opt/magenx/config/`
