### ISSUE TITLE
install log?

### ISSUE THREAD

**Issue by gfxguru** [magenx/Magento-2-server-installation#166]
I noticed there is not install.log file anymore in the opt/magenx/config dir. Plus what is the new magenx.lock file?

**Comment by gfxguru** [comment]
Also phpmyadmin config?

**Comment by gfxguru** [comment]
and mysql root does not have a password. Is this intentional?

**Comment by magenx** [comment]
install log printed  and saved at the end
phpmyadmin config the same
mysql root password also generated

**Comment by gfxguru** [comment]
mysql root does not have a password and I can't find install.log on latest build it's no longer in magenx/config. older builds yes.

**Comment by gfxguru** [comment]
where is the install.log? I can't seem to find it on my install

**Comment by gfxguru** [comment]
sorry, I just did another install and the install.log is in the opt/magenx/config folder.
