### ISSUE TITLE
Not an issue, could be a feature request?

### ISSUE THREAD

**Issue by gfxguru** [magenx/Magento-2-server-installation#167]
I want to add other php code to the magento install but having issues I'm guessing because of the public_html.acl file. If I want to add say a chat system to magento and it has php code, do I need to add the files to this acl?

**Comment by magenx** [comment]
you need to deploy with the same user as magento owner
or you need to fix permissions

**Comment by gfxguru** [comment]
I'm unable to execute php code. Do I need to add the php code to the ACL created by magenx?
