### ISSUE TITLE
Cannot open: jre-8u202-linux-x64.rpm.

### ISSUE THREAD

**Issue by wolfautoparts** [magenx/Magento-2-Server-Installation#168]
Java and Elasticsearch issues. Same issues on clean centos 7 vultr and digitalocean servers.

**Comment by magenx** [comment]
you cantry this command:
`wget --no-cookies --no-check-certificate --header "Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie" "https://download.oracle.com/otn-pub/java/jdk/8u202-b08/1961070e4c9b4e26a04e7f5a083f551e/jre-8u202-linux-x64.rpm"`
