### ISSUE TITLE
Idea to add logrotate for logs?

### ISSUE THREAD

**Issue by seansan** [magenx/Magento-2-Server-Installation#170]
Stored in /etc/logrotate.d/httpd

# Rotate logs for magento
/var/www/html/m2/*/var/log/*.log {
    daily
    compress
    size 50M
    rotate 4
    create 0664
    missingok
    notifempty
}

Not really necessary but will maybe help you that one time when log explodes

**Comment by magenx** [comment]
yes, it is already built in stack configuration:

https://github.com/magenx/Magento-2-Server-Installation/blob/master/Magento-2/CentOS-7/magenx.sh#L1297

**Comment by seansan** [comment]
I saw this in your scripts, but we did not have this at our server yet I think
I created the file magento
