### ISSUE TITLE
Magento slow with 5000 products

### ISSUE THREAD

**Issue by Veltix** [magenx/Magento-2-server-installation#176]
Magento slow with 5000 products.

I have one category over 2000+ products and it loads 3.2 minutes.

Enabled / Disabled FPC cache and result is same..

Varnish not working? or elasticsearch not working?
I can see that mysql using 50% - 70% memory.

I have 32GB ram.

-----------------
Mysqltuner:

[--] Up for: 55d 9h 10m 57s (1B q [297.161 qps], 3M conn, TX: 5084G, RX: 438G)
[--] Reads / Writes: 76% / 24%
[--] Binary logging is disabled
[--] Physical Memory     : 30.6G
[--] Max MySQL memory    : 48.1G
[--] Other process memory: 0B
[--] Total buffers: 10.3G global + 258.3M per thread (150 max threads)
[--] P_S Max memory usage: 0B
[--] Galera GCache Max memory usage: 0B
[!!] Maximum reached memory usage: 36.5G (119.30% of installed RAM)
[!!] Maximum possible memory usage: 48.1G (157.19% of installed RAM)
[!!] Overall possible memory usage with other process exceeded memory

**Comment by fvlasie** [comment]
Should your max memory exceed your physical memory? Something tells me max memory should be around 16GB. You are probably letting MySQL use too much  RAM forcing everything into the swamp...

See https://stackoverflow.com/questions/71984064/mysql-maximum-memory-dangerously-high-mariadb-optimization

**Comment by magenx** [comment]
you need to run profiler
if you like to see more data you need newrelic

profiler is already configured in nginx
https://github.com/magenx/Magento-nginx-config/blob/master/magento2/conf_m2/maps.conf#L25
https://github.com/magenx/Magento-nginx-config/blob/master/magento2/sites-available/magento2.conf#L100
