### ISSUE TITLE
nginx: [emerg] zero size shared memory zone "zone3"

### ISSUE THREAD

**Issue by jorgb90** [magenx/Magento-2-server-installation#177]
Direct after clean install nginx is not starting because of:

Feb 15 14:48:53 systemd[1]: Starting nginx - high performance web server...
Feb 15 14:48:54 nginx[807]: nginx: [emerg] zero size shared memory zone "zone3"
Feb 15 14:48:54 systemd[1]: nginx.service: Control process exited, code=exited, status=1/FAILURE
Feb 15 14:48:54 systemd[1]: nginx.service: Failed with result 'exit-code'.
Feb 15 14:48:54 systemd[1]: Failed to start nginx - high performance web server.

**Comment by magenx** [comment]
it is fixed now
zone name must be configured before 

new zone "search" was created in nginx config
https://github.com/magenx/Magento-nginx-config/tree/master/magento2
