### ISSUE TITLE
will this configure Auto Scaling Architecture on the server?

### ISSUE THREAD

**Issue by VivekShingala** [magenx/Magento-2-server-installation#18]
Hi

This repo seems to be interesting. If we do all the setups, will it be already configured for auto scaling or load balancing to handle heavy traffic on the website?

**Comment by magenx** [comment]
no
this is only to setup one server.
for auto scaling you have to use simplified config, when you start new server using cloud config on the fly install webstack and mount your disk/storage with shared files, then you have to update load balancer with IP, etc

**Comment by VivekShingala** [comment]
Thanks I'll try setting up the server as you suggested.
