### ISSUE TITLE
Moving to OpenSearch

### ISSUE THREAD

**Issue by gfxguru** [magenx/Magento-2-server-installation#180]
I'm ready to get rid of Elastic.

**Comment by jorgb90** [comment]
Would perhaps be a good idea. Havent tested this yet.

**Comment by magenx** [comment]
there is no difference for magento use case

**Comment by artmouse** [comment]
> there is no difference for magento use case

By default Magento 2.4.6 use Opensearch when installed.

**Comment by gfxguru** [comment]
just don't install. sounds easy enough

**Comment by magenx** [comment]
ok, looks like right now magento 2.4.6 not working with elasticsearch 8
there is no such module, probably going to OpenSearch...

**Comment by magenx** [comment]
is thre anyone actually able to install magento 2.4.6 with opensearch using authentication?

**Comment by magenx** [comment]
right now installed elasticsearch 8.6 with --search-engine=opensearch enable authentication with disabled ssl...
again magento "A feature, not a bug" approach...

**Comment by artmouse** [comment]
> right now installed elasticsearch 8.6 with --search-engine=opensearch enable authentication with disabled ssl... again magento "A feature, not a bug" approach...

Error received plaintext http traffic on an https channel, closing connection
FIX add parameter - xpack.security.enabled=false

**Comment by artmouse** [comment]
There are many problems with the new version of the elastic search engines. You need to update the magento lib manually. I still recommend using the elasticsearch version 7.17

**Comment by magenx** [comment]
lets wait for magento 2.4.7

**Comment by magenx** [comment]
https://github.com/magento/magento2/issues/37236

**Comment by magenx** [comment]
OpenSearch releases 2.12
https://github.com/orgs/opensearch-project/projects/1#column-19500379

**Comment by magenx** [comment]
now available opensearch 2.13
