### ISSUE TITLE
Oracle Cloud Instance ARM Support

### ISSUE THREAD

**Issue by fvlasie** [magenx/Magento-2-server-installation#181]
Hello!

Is there any chance of adding OCI ARM support?
You already support Graviton so perhaps it is as simple as adding OL9 to the checklist?

Thank you!

**Comment by magenx** [comment]
any errors you have?
you can try to remove / adjust OS check and install

but the next version 246 will only support Debian >11 and Ubuntu LTS
there is no point in supporting so many systems.

**Comment by fvlasie** [comment]
No more RHEL support? Oh no...
