### ISSUE TITLE
Testing on OCI ARM

### ISSUE THREAD

**Issue by fvlasie** [magenx/Magento-2-server-installation#186]
Hello! 

I am testing the install script on Ubuntu 20.04 on an OCI ARM server and most of it seems to be fine but I am seeing this error when running "install"

```
  [-] Magento 2.4.5-p1 ready to be installed for production environment

  [!] Press [Enter] key to run setup:install

Command option 'timezone': Invalid value. To see possible values, run command 'bin/magento info:timezone:list'.

In InstallCommand.php line 282:
                               
  Parameter validation failed  
                               
```

**Comment by fvlasie** [comment]
I will try 
```
timedatectl set-timezone 'America/Los_Angeles'
```

**Comment by fvlasie** [comment]
OK that worked! I set the timezone before executing magenx.sh

**Comment by fvlasie** [comment]
I have completed all the srcipts successfully but when I open the admin URL I am seeing a Guru meditation error. The nginx logs show:

```
127.0.0.1 - - [22/Mar/2023:23:12:44 -0700] "GET http://localhost/health_check.php HTTP/1.1" 404 541 "-" "-" 0.000 - "6cbc3e7044439467fbd22b59d7f309f0"
```

**Comment by magenx** [comment]
i see, strange error,
the script at the beginning asks to set the timezone,
did you set the timezone from the script? what was the timezone?

**Comment by fvlasie** [comment]
First time I set the timezone to US/Pacific with the script but that is apparently not compatible with Magento.

**Comment by fvlasie** [comment]
I can provide access to an OCI instance if you would like to test it.

**Comment by fvlasie** [comment]
I just ran the install script on a fresh instance and it worked! 
I skipped the CSF firewall and the webadmin. 
Nginx SEGVd once after running certbot to obtain certificates but a restart of nginx seems to be working.
I will keep testing it for a while and let you know.
But it seems that OCI instances can be listed as supported now!

**Comment by fvlasie** [comment]
After disabling the two-factor auth module I am getting the following error in system.log when trying to access the admin:

```
[2023-03-24T18:48:33.803003+00:00] main.CRITICAL: Can't create directory /home/ubuntu/public_html/generated/code/Magento/Backend/Model/Url/.
Class Magento\Backend\Model\Url\Interceptor generation error: The requested class did not generate properly, because the 'generated' directory permission is read-only. If --- after running the 'bin/magento setup:di:compile' CLI command when the 'generated' directory permission is set to write --- the requested class did not generate properly, then you must add the generated class object to the signature of the related construct method, only. [] []
[2023-03-24T18:48:33.803208+00:00] main.CRITICAL: Error: Class "Magento\Backend\Model\Url\Interceptor" not found in /home/ubuntu/public_html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:121
```
I have tried fixing the permissions (even setting the generated diretory to 777) but the error persists...

I am not sure what to try next.

**Comment by fvlasie** [comment]
OK I think I need the development version...

BTW, curl is saying the certificate for magenx is expired:

```
root@magenx-dev:/home/ubuntu# curl -Lo magenx.sh https://magenx.sh && bash magenx.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   138  100   138    0     0    221      0 --:--:-- --:--:-- --:--:--   221
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (60) SSL certificate problem: certificate has expired
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

**Comment by fvlasie** [comment]
Oh, it is githubusercontent.com that has expired! 🙄 

<img width="631" alt="Screenshot 2023-03-24 at 1 54 23 PM" src="https://user-images.githubusercontent.com/33334298/227638011-e96e51fc-e427-4a55-adf1-fa8d14db87b5.png">

**Comment by fvlasie** [comment]
OK. I installed the developer version but now I get a "curl: (52) Empty reply from server" when trying to access the server over http.

**Comment by fvlasie** [comment]
The problem was not the empty reply (which is what happens with curl) but a blocked port. Running:

```
iptables -I INPUT 6 -m state --state NEW -p tcp --dport 80 -j ACCEPT
netfilter-persistent save
```
solved the problem!

**Comment by fvlasie** [comment]
OK I can confirm that the Magenx installation works on OCI instances!

Thank you @magenx !
