### ISSUE TITLE
Magento 2.4.1 installation error

### ISSUE THREAD

**Issue by VivekShingala** [magenx/Magento-2-server-installation#19]
Hi, I am trying to setup server on my aws instance and getting below error on the Magento installation step.

```
Problem 1
- Root composer.json requires magento/composer-root-update-plugin ~1.0 -> satisfiable by magento/composer-root-update-plugin[1.0.0].
- magento/composer-root-update-plugin 1.0.0 requires composer-plugin-api ^1.0 -> found composer-plugin-api[2.0.0] but it does not match the constraint.
Problem 2
- Root composer.json requires dealerdirect/phpcodesniffer-composer-installer ^0.5.0 -> satisfiable by dealerdirect/phpcodesniffer-composer-installer[v0.5.0].
- dealerdirect/phpcodesniffer-composer-installer v0.5.0 requires composer-plugin-api ^1.0 -> found composer-plugin-api[2.0.0] but it does not match the constraint.
Problem 3
- laminas/laminas-dependency-plugin[1.0.0, ..., 1.0.4] require composer-plugin-api ^1.1 -> found composer-plugin-api[2.0.0] but it does not match the constraint.
- magento/product-community-edition 2.4.1 requires laminas/laminas-dependency-plugin ^1.0 -> satisfiable by laminas/laminas-dependency-plugin[1.0.0, ..., 1.0.4].
- Root composer.json requires magento/product-community-edition 2.4.1 -> satisfiable by magento/product-community-edition[2.4.1].

You are using Composer 2, which some of your plugins seem to be incompatible with. Make sure you update your plugins or report a plugin-issue to ask them to support Composer 2.
```

**Comment by magenx** [comment]
the magic of Magento 2 
it only works with composer <1.x

installation script now locked with composer version 1.10.16

**Comment by VivekShingala** [comment]
Thanks, I found it [here](https://magento.stackexchange.com/a/325299) but CentOs 8 was not letting me downgrade it.

Should I re-run the `lemp` installation on the same server to fix it?

**Comment by VivekShingala** [comment]
That worked running lemp installation again. However, facing new error related to Elasticsearch.

```
In SearchConfig.php line 81:
Could not validate a connection to Elasticsearch. The search failed because of a search engine misconfiguration.

```

[https://snipboard.io/XB4oGn.jpg](https://snipboard.io/XB4oGn.jpg)

**Comment by magenx** [comment]
need to test it

**Comment by VivekShingala** [comment]
Also couple of below errors in the `config` step. 

![https://snipboard.io/Tk3M0n.jpg](https://snipboard.io/Tk3M0n.jpg)

![https://snipboard.io/Sc2JtY.jpg](https://snipboard.io/Sc2JtY.jpg)

**Comment by VivekShingala** [comment]
We got two more errors one was related to Elasticsearch and other was for redis.

**Elasticsearch Error**
```
Oct 30 15:17:26 server systemd-entrypoint[332572]: Exception in thread "main" 2020-10-30 15:17:26,079 main ERROR No Log4j 2 configuration file found. Using default conf>
Oct 30 15:17:26 server systemd-entrypoint[332572]: SettingsException[Failed to load settings from [elasticsearch.yml]]; nested: JsonParseException[Duplicate field 'disc>
Oct 30 15:17:26 server systemd-entrypoint[332572]:  at [Source: (sun.nio.ch.ChannelInputStream); line: 91, column: 15]];
Oct 30 15:17:26 server. systemd-entrypoint[332572]: Caused by: com.fasterxml.jackson.core.JsonParseException: Duplicate field 'discovery.type'
Oct 30 15:17:26 server systemd-entrypoint[332572]:  at [Source: (sun.nio.ch.ChannelInputStream); line: 91, column: 15]
Oct 30 15:17:26 server systemd-entrypoint[332572]:         ... 9 more
Oct 30 15:17:26 server systemd[1]: elasticsearch.service: Main process exited, code=exited, status=1/FAILURE
Oct 30 15:17:26 server systemd[1]: elasticsearch.service: Failed with result 'exit-code'.
Oct 30 15:17:26 server systemd[1]: Failed to start Elasticsearch.
lines 309-365/365 (END)
```

**Elasticsearch Fix**
Find and remove duplicate lines for below in elasticsearch.yml
```
discovery.type: single-node
xpack.security.enabled: true
```


We found another error for redis.

**Redis error**
```
[root@server:public_html]$ rm -rf pub/static/ && rm -rf var/view_preprocessed/ && bin/magento set:up
Connection to Redis 127.0.0.1:6380 failed after 2 failures.Last Error : (1) Connection refused
```

**Redis fix**
```
redis.conf  
default port changed to 6378 in this file as 6379 port used in redis-6379.conf
```



After above fixes we again tried install step to setup Magento but we got below error.
![https://snipboard.io/Ymo7vW.jpg](https://snipboard.io/Ymo7vW.jpg)

How do we fix permission related errors?

**Comment by magenx** [comment]
it looks like you run this multiple times,
this is a one way installation

you have to run it clean again

**Comment by VivekShingala** [comment]
We started on a new instance but yes, we had to run it multiple times the `lemp` step. But for Magento installation we cleared public_html directory for a successful `magento` step.

So, if anything fails during `lemp` step, we need to clear the instance and start it all over again or you are saying if any particular service like `redis` or `elasticsearch` fails then we need to remove it particularly and start again.

**Comment by magenx** [comment]
lemp is only packages installation, you can run it many times

**Comment by VivekShingala** [comment]
So, how do we fix the errors mentioned in this issue?

**Comment by magenx** [comment]
running this installation without any issues
