### ISSUE TITLE
Installation Log 

### ISSUE THREAD

**Issue by musabatas** [magenx/Magento-2-server-installation#191]
I can't see the 'Installation Log'. How can I see the log file after installation?

**Comment by magenx** [comment]
you have to use `sqlite3`
config and all output saved into sqlite database.

**magento:**
`sqlite3 -line /opt/magenx/config/magenx.db "SELECT * FROM magento;"`
  
**system:**
`sqlite3 -line /opt/magenx/config/magenx.db "SELECT * FROM system;"`
