### ISSUE TITLE
Switching Developer install to Production 404 css js

### ISSUE THREAD

**Issue by fvlasie** [magenx/Magento-2-server-installation#192]
Hello,

I have installed developer mode from Magenx script. When switching to production mode (bin/magento deploy:mode:set production) the site gives 404s for all the css and js.

```
[Error] Failed to load resource: the server responded with a status of 404 () (calendar.css, line 0) /static/version1679861510/frontend/Magento/luma/en_US/mage/calendar.css
...
```
 
I have reset permissions, di:compiled, deployed, but I cannot resolve the issue. Does the developer install from magenx work in Magento production mode?

**Comment by magenx** [comment]
first of all you dont have to switch mode. and change anything on the server.
proper development CI/CD is when you `deploy` code from `github` using `github actions`
and then `setup:upgrade` if needed and reload the cache all with deployment script
all this in its own existing environment. you have already environmetal variables. ssh keys. permissions set. etc

developer -> staging -> production
developer done some changes, deploy to staging, changes confirmed, create release, deploy release to production.
you dont have to login to your server at all.

**Comment by fvlasie** [comment]
Thank you for the reply! 

So I would need three servers, developer (could be local VM), staging, and production. Each server has been deployed with magenx.sh according to it's role.

The two github actions:
1. Push changes from Developer to Staging
2. Push changes from Staging to Production

Is that the right idea?

**Comment by magenx** [comment]
it can be 3 servers or single server with 3 environments
you deploy any build you have, with git it is very fast
with github actions you can script many steps

**Comment by fvlasie** [comment]
Interesting! If I have all three environments on one machine, can I update production by rsyncing the Magento root folders?

**Comment by magenx** [comment]
no
