### ISSUE TITLE
cron does not appear to be set up

### ISSUE THREAD

**Issue by fvlasie** [magenx/Magento-2-server-installation#194]
Hello!

I am testing a set up with a triple dev, staging, and production install and it seems that cron jobs have not been configured.

Do I need to run bin/magento cron:install for all three magento installations?

Thank you!

**Comment by magenx** [comment]
cron installed from here
https://github.com/magenx/Magento-2-server-installation/blob/c892b401e1975c26a93c3d1f3227b88be7b9cb0d/magenx.install.latest.sh#L2010

**Comment by fvlasie** [comment]
When I run `crontab -l`
I see: `no crontab for user` where `user` is the php user.

**Comment by fvlasie** [comment]
OK so I can fix the crontab but now I see this error when running the jobs:

```
Sales Order Feed index process error during indexation process:
Class "Magento\Analytics\ReportXml\Config\Converter\Xml" does not exist
Sales Order Statuses Feed index process error during indexation process:
Class "Magento\Analytics\ReportXml\Config\Converter\Xml" does not exist
Stores Feed index process error during indexation process:
Class "Magento\Analytics\ReportXml\Config\Converter\Xml" does not exist
```

**Comment by fvlasie** [comment]
Upon further investigation it seems Magenx is missing the Magento_Analytics modules...
