### ISSUE TITLE
Too many redirects on Admin

### ISSUE THREAD

**Issue by fvlasie** [magenx/Magento-2-server-installation#195]
Hello!

I am getting too many redirects on Admin after enabling setting the secure base URL to "https"

I cannot change it back to "http" because 1) I cannot access the admin web gui and 2) bin/magento setup will not allow values for secure-base-url that do not start with https.

Is there a nginx https redirect at play here?

Thank you

**Comment by magenx** [comment]
make sure you have unsecure set to https too
and add 
`fastcgi_param   HTTPS   on;`
to php_backend

**Comment by fvlasie** [comment]
Thank you very much for the feedback! I think I found the solution!

`fastcgi_param  HTTPS              $https if_not_empty;`is already set.

I found that I needed to uncomment the following lines in /etc/nginx/conf_m2/varnish_proxy.conf

```
#   proxy_set_header X-Scheme https;
#   proxy_set_header X-Forwarded-Proto https;
#   proxy_set_header X-Forwarded-Port 443;
#   proxy_set_header X-Secure on;
```
