### ISSUE TITLE
Multi store with one domain

### ISSUE THREAD

**Issue by fvlasie** [magenx/Magento-2-server-installation#196]
Hello!

I am trying to transfer Magento from an install with two storefronts using store codes and one domain.

I found the issue here https://github.com/magenx/Magento-2-server-installation/issues/105 but I am not sure where to put what codes.

I have edited these files (as below) but perhaps I am misunderstanding something because I am getting a whole bunch of 404s when loading the frontend and admin.

Thank you!

`/etc/nginx/sites-available/magento2.conf`

```
     ## Store code with multi domain
    fastcgi_param   MAGE_RUN_CODE $MAGE_RUN_CODE;
    fastcgi_param   MAGE_RUN_TYPE $MAGE_RUN_TYPE;
```

`/etc/nginx/sites-available/dev.site.com.conf`

```
     ## Store code with multi domain
    fastcgi_param   ecs $MAGE_RUN_CODE;
    fastcgi_param   storefront $MAGE_RUN_TYPE;
```

`/etc/nginx/conf_m2/maps.conf`

```
## Multi shop code configuration
map $http_host $MAGE_RUN_CODE {
hostnames;
        .site.com ecs;
}

map $http_host $MAGE_RUN_TYPE {
hostnames;
#        .site.com store;
        .site.com website;
}
```

**Comment by magenx** [comment]
you only need to add domain and code to maps config
nothing more to change

**Comment by fvlasie** [comment]
Thank you!
