### ISSUE TITLE
RabbitMQ 3.11* installation error

### ISSUE THREAD

**Issue by musabatas** [magenx/Magento-2-server-installation#214]
`rabbitmq-server : Depends: erlang-base (< 1:26.0) but 1:26.1.2-1 is to be installed or
                            erlang-base-hipe (< 1:26.0) but it is not going to be installed or
                            esl-erlang (< 1:26.0) but it is not installable
                   Depends: erlang-crypto (< 1:26.0) but 1:26.1.2-1 is to be installed or
                            esl-erlang (< 1:26.0) but it is not installable
                   Depends: erlang-eldap (< 1:26.0) but 1:26.1.2-1 is to be installed or
                            esl-erlang (< 1:26.0) but it is not installable
                   Depends: erlang-inets (< 1:26.0) but 1:26.1.2-1 is to be installed or
                            esl-erlang (< 1:26.0) but it is not installable
                   Depends: erlang-mnesia (< 1:26.0) but 1:26.1.2-1 is to be installed or
                            esl-erlang (< 1:26.0) but it is not installable
                   Depends: erlang-os-mon (< 1:26.0) but 1:26.1.2-1 is to be installed or
                            esl-erlang (< 1:26.0) but it is not installable
                   Depends: erlang-parsetools (< 1:26.0) but 1:26.1.2-1 is to be installed or
                            esl-erlang (< 1:26.0) but it is not installable
                   Depends: erlang-public-key (< 1:26.0) but 1:26.1.2-1 is to be installed or
                            esl-erlang (< 1:26.0) but it is not installable
                   Depends: erlang-runtime-tools (< 1:26.0) but 1:26.1.2-1 is to be installed or
                            esl-erlang (< 1:26.0) but it is not installable
                   Depends: erlang-ssl (< 1:26.0) but 1:26.1.2-1 is to be installed or
                            esl-erlang (< 1:26.0) but it is not installable
                   Depends: erlang-syntax-tools (< 1:26.0) but 1:26.1.2-1 is to be installed or
                            esl-erlang (< 1:26.0) but it is not installable
                   Depends: erlang-tools (< 1:26.0) but 1:26.1.2-1 is to be installed or
                            esl-erlang (< 1:26.0) but it is not installable
                   Depends: erlang-xmerl (< 1:26.0) but 1:26.1.2-1 is to be installed or
                            esl-erlang (< 1:26.0) but it is not installable
E: Unable to correct problems, you have held broken packages.`

Tried in 22.04 and 20.04. RabbitMQ installation failed.

**Comment by magenx** [comment]
this will be fixed now
#215
