### ISSUE TITLE
updated default.vcl config 503 Error varnish 6

### ISSUE THREAD

**Issue by Wakie87** [magenx/Magento-2-server-installation#22]
https://github.com/magenx/Magento-2-server-installation/blob/40ec1783b391200ac99559a87c716bfb2e4f4e89/default.vcl#L18

The default magento configuration adds a couple of extra lines to prevent 503 error. (See below link)
[https://github.com/magento/magento2/issues/24353#issuecomment-592038624](url)

`sub vcl_recv {`     
`if (req.restarts > 0) {`
`        set req.hash_always_miss = true;`
`    }`

**Comment by magenx** [comment]
removed this file now

varnish config generated from magento
