### ISSUE TITLE
Server upgrade

### ISSUE THREAD

**Issue by teodorpav** [magenx/Magento-2-server-installation#27]
Hi,
after installing I can't upgrade the server:

[root@server:dev]$ dnf upgrade
varnishcache_varnish64                                                                                                              320  B/s | 833  B     00:02    
varnishcache_varnish64-source                                                                                                       436  B/s | 833  B     00:01    
Error: 
 Problem: package varnish-6.4.0-1.el8.x86_64 requires libjemalloc.so.2()(64bit), but none of the providers can be installed
  - cannot install both jemalloc-1:3.6.0-1.el8.x86_64 and jemalloc-5.2.1-2.el8.x86_64
  - cannot install the best update candidate for package varnish-6.4.0-1.el8.x86_64
  - cannot install the best update candidate for package jemalloc-5.2.1-2.el8.x86_64
(try to add '--allowerasing' to command line to replace conflicting packages or '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)

If I'm using "--allowerasing" Varnish is deleted.
"--skip-broken" - doesn't work.

Thank you

**Comment by magenx** [comment]
there are multiple ways to fix this repo conflict, like
use `priority=1` plugin config, to give master repo higher priority for installing new updates and packages with higher versions.
`exclude= ` exact package name in main `yum.conf` or from .repo config, exclude `-x` exact package name in command line when installing / updating

```
yum whatprovides jemalloc
Last metadata expiration check: 0:07:04 ago on Sun 24 Jan 2021 02:14:05 PM -03.
jemalloc-5.2.1-2.el8.x86_64 : General-purpose scalable concurrent malloc implementation
Repo        : @System
Matched from:
Provide    : jemalloc = 5.2.1-2.el8

jemalloc-5.2.1-2.el8.x86_64 : General-purpose scalable concurrent malloc implementation
Repo        : epel
Matched from:
Provide    : jemalloc = 5.2.1-2.el8

jemalloc-1:3.6.0-1.el8.x86_64 : General-purpose scalable concurrent malloc implementation
Repo        : ps-57-release-x86_64
Matched from:
Provide    : jemalloc = 1:3.6.0-1.el8
```
