### ISSUE TITLE
Few errors

### ISSUE THREAD

**Issue by teodorpav** [magenx/Magento-2-server-installation#3]
Hi,
during the last step of the installation I received few errors:

sysctl: cannot stat /proc/sys/net/ipv4/tcp_tw_recycle: No such file or directory

                NGINX SETTINGS
sed: can't read /etc/nginx/sites-available/magento2.conf: No such file or directory
sed: can't read /etc/nginx/sites-available/magento2.conf: No such file or directory
sed: can't read /etc/nginx/conf_m2/extra_protect.conf: No such file or directory

                PHPMYADMIN INSTALLATION AND CONFIGURATION
Failed to download metadata for repo 'varnishcache_varnish64'
Error: Failed to download metadata for repo 'varnishcache_varnish64'
sed: can't read /etc/phpMyAdmin/config.inc.php: No such file or directory
sed: can't read /etc/nginx/conf_m2/phpmyadmin.conf: No such file or directory
sed: can't read /etc/nginx/conf_m2/phpmyadmin.conf: No such file or directory

I've noticed that the /etc/resolv.conf is cleared by the script (I've checked the file before installation).
When I modified /etc/resolv.conf and run the "> config" step again installation is finished without errors but the site doesn't work , phpmyadmin also doesn't work.

I can't login SSH and SFTP with magento [files owner] credentials.

Thank you

Centos 8.1 minimal

**Comment by magenx** [comment]
right, `tcp_tw_recycle ` removed

for now created network test before config run
