### ISSUE TITLE
Your system is not supported by certbot-auto anymore

### ISSUE THREAD

**Issue by ilevennet** [magenx/Magento-2-server-installation#30]
Trying to generate certs happen this.

[root@server:~]$ certbot-auto renew --cert-name domain name.ext
Skipping bootstrap because certbot-auto is deprecated on this system.
Your system is not supported by certbot-auto anymore.
Certbot cannot be installed.
Please visit https://certbot.eff.org/ to check for other alternatives.

using procedures explained on https://certbot.eff.org/  all is ok

**Comment by magenx** [comment]
changed to `snapd ` installation
as recommended from letsencrypt

**Comment by volanar** [comment]
> changed to `snapd ` installation
> as recommended from letsencrypt

I think snapd should be added to the install command. I spent several hours installing the script until I noticed that snapd is not being installed
