### ISSUE TITLE
Missing packages

### ISSUE THREAD

**Issue by marcinex** [magenx/Magento-2-server-installation#32]
Hi

In Ubuntu (Hetzner) I had to install snap snapd goaccess python3-dev before. Otherwise, I have errors.
In Debian 10 script hangs on php-lz4 (no matter what php I choose). The solution is to add  https://packages.sury.org/php/ repository. Next problem is with rabbitMq - it wont work because it needs glibc >= 2.29 and Debian gives only 2.28.

Anyway - great script! :) Thank You for grat work.

**Comment by magenx** [comment]
there will be much better when Debian 11 this summer and later ubuntu 22.lts comes out,
but for now there is a mess with packages names and versions, compatibility, etc
not easy to align everything
