### ISSUE TITLE
No commands defined in 'sampledata' section

### ISSUE THREAD

**Issue by skazhikadyadya** [magenx/Magento-2-server-installation#35]
Hi. When i try to execute `bin/magento sampledata:deploy` I see error: `There are no commands defined in the "sampledata" namespace.`

Ubuntu 20, latest Magento 2.4.2-p1, clear Magenx installation.

How i can solve that? Thanks!

**Comment by magenx** [comment]
if you have sampledata module replaced in composer.json, you need to remove it and run composer update
