### ISSUE TITLE
Problem with MediaGallerySynchronizationApi

### ISSUE THREAD

**Issue by skazhikadyadya** [magenx/Magento-2-server-installation#36]
Ubuntu 20, Magento 2.4.2-p1. Trying to install Amasty Jet Theme. Doing:

```
composer require amasty/jet-theme
bin/magento setup:upgrade
```
Get error: `"Class Magento\MediaGallerySynchronizationApi\Api\SynchronizeFilesInterface does not exist".`

Flush cache with /usr/local/bin/cacheflush - and `setup:upgrade` - same result.

Remove line `"magento/module-media-content-synchronization-api": "*",` from composer.json - no effect. 

Any ideas?

**Comment by skazhikadyadya** [comment]
Fixed by removing section "replace" in composer.json.

**Comment by magenx** [comment]
you will get all available modules and its dependencies installed.
