### ISSUE TITLE
PHP FPM Pool Conf

### ISSUE THREAD

**Issue by areebmoin** [magenx/Magento-2-server-installation#37]
Please change line 1410 in magenx.install.8.sh for pm.max_children setting to be updated.

from 

sed -i 's/pm.max_children = 50/pm.max_children = 1000/' ${php_fpm_pool}

to

sed -i 's/pm.max_children = 5/pm.max_children = 1000/' ${php_fpm_pool}

**Comment by magenx** [comment]
this is fixed now
thank you
