### ISSUE TITLE
Permissions for uploaded files

### ISSUE THREAD

**Issue by skazhikadyadya** [magenx/Magento-2-server-installation#39]
Hello.

I has latest MagenX stack on Ubuntu 20. When I upload the images they are correctly displayed in the magento admin. After save and refresh page in admin i see only empty squares. 

When i do `ls -alh` I see that permissions:
```
drwxrws---+ 2 php-magento php-magento 4.0K May 27 05:13 .
drwxrws---+ 4 php-magento php-magento 4.0K May 26 14:48 ..
-rwxrwx---  1 php-magento php-magento  31K May 27 05:13 01_1.jpg
-rwxrwx---  1 php-magento php-magento  31K May 26 14:47 01.jpg
```

When I try to get image directly on browser i see 502 error and `13: Permission denied` in the log file. 

How I can solve it? Thank you!

**Comment by skazhikadyadya** [comment]
Fixed by changing php-magento to magento in php-fpm configuration.

**Comment by magenx** [comment]
need to check ACL settings `getfacl`, looks like not set
