### ISSUE TITLE
502 Bad Gateway nginx, or 503 Backend fetch failed with varnish

### ISSUE THREAD

**Issue by karamucho** [magenx/Magento-2-server-installation#4]
I installed several times on centos stream 8, with varnish installed every time I get a 503 error Backend fetch failed, if I don't install varnish then 502 Bad Gateway nginx, the certbot installation also failed because of this, is this a bug or my fault?

**Comment by divisum** [comment]
Remove .probe at varnish default.vcl

**Comment by jbutkowski** [comment]
I'm experiencing the same issue as @karamucho - including certbot installation failure.

I've removed .probe from varnish default.vcl and restarted varnish - however this did not resolve the issue.

**Comment by divisum** [comment]
> I'm experiencing the same issue as @karamucho - including certbot installation failure.
> 
> I've removed .probe from varnish default.vcl and restarted varnish - however this did not resolve the issue.

Almost certain that magento is trying to reach https version of the site, but since certbot failed you will have to modify nginx configuration file and listen 433 is commented.

There are several solutions: you can create a self signed certificate and modify nginx conf, or pass varnish or disable varnish proxy (in this case you must garantee that magento will allow http without redirecting to https)

**Comment by karamucho** [comment]
Removing .probe from varnish default.vcl before installing letsencrypt allowed the certificate to be installed, but despite the fact that the installation passed flawlessly https does not work and http causes a redirect loop on every browser, the problem must be somewhere between ssl, nginx and varnish, but where to look for it ?

**Comment by divisum** [comment]
In my version, i always generate a self signed ssl and uncomment the port 443 and attach the crt and key to nginx config. 
That way will always work because https will be available. After that you run certbot. 
In my opinion is the most reliable way. Never fails

**Comment by magenx** [comment]
for now this part is a bit confusing,
so probably better:
- comment varnish probe
- get cert with webroot
- enable ssl in nginx / proxy
- reload nginx

**Comment by orbisunom** [comment]
Hello this is normal to Magento 2 

You need to update the /etc/varnish/default.vlc 
Note this is for magento 2 lastest 2.3.5.p1 
for magento 2.3.1 ---> 2.3.3 you need to update file /pub/health_check.php (Please Just Google it as I forgot already the link) and also update the default.vlc


backend default {
    .host = "localhost";
    .port = "8080";
    .first_byte_timeout = 600s;
    .probe = {
        .url = "/health_check.php";
        .timeout = 2s;
        .interval = 5s;
        .window = 10;
        .threshold = 5;
   }
}

and your site is working

BTW

on nginx.conf 
you need to have **event{}** just add this and restart your nginx  to be able to start Nginx service

**Comment by seiya74656** [comment]
After about 10times installing a server with this script. For me worked now.

Give the machine a hostname before installation
hostnamectl set-hostname server.yourdomain.com --static

Disable selinux

Check if DNS / Connection are working (after that my DNS Servers was not working anymore)
ping google.com , Set new DNS Server with nmtui / cmcli (ex. 1.1.1.1 , 1.0.0.1) 
---
There is also a little bug in the code, change the line before installation
from
redis-cli -p6380 flushall
to
redis-cli -p 6380 flushall

If lets encrypt error in installation , create a new certificate and run certbot again. 
certbot-auto

Restart Services:
systemctl restart nginx varnish

Clear Magento Cache
php bin/magento cache:clean
