### ISSUE TITLE
No ssl 

### ISSUE THREAD

**Issue by BambooLnd** [magenx/Magento-2-server-installation#40]
Can anyone tell me what settings should I change so that SSL works for me? 
I noticed that port 443 is not listening. 
And phpmyadmin is not displaying correctly

**Comment by magenx** [comment]
you need to change nginx config, installed from here:
uncomment lines `5 - 14`, `19`, `43`,`44`
https://github.com/magenx/Magento-nginx-config/blob/master/magento2/sites-available/magento2.conf

uncomment lines `9 - 12`
https://github.com/magenx/Magento-nginx-config/blob/master/magento2/conf_m2/varnish_proxy.conf

you must have cert already,
or if you know how to re-use certbot commands to re-issue

**Comment by BambooLnd** [comment]
Thanks for your help, you are great.
I can't wait to see your scrypt compatible with RedHat 8.3
