### ISSUE TITLE
Support Centos 8 Stream

### ISSUE THREAD

**Issue by teodorpav** [magenx/Magento-2-server-installation#46]
Hi,
my Contabo VPS allow installation only Centos 8 Stream but the script not support it.
Will you add support of the Stream?

Thank you

**Comment by magenx** [comment]
CentOS X is dead end.

please migrate to Ubuntu 20.04 or better to Debian 11
there are lots of providers

https://www.magenx.com/blog/post/the-best-hosting-server-for-magento-2.html

AWS also support every distro + reserved instance discounts
