### ISSUE TITLE
Varnish Problem

### ISSUE THREAD

**Issue by mucan54** [magenx/Magento-2-server-installation#47]
I followed the steps to setup magento 2 as bash menu described, I added my domain. Everything is done successfully but at the end I can not reach the site. When I check ngnix acces.log I see that log:

127.0.0.1 - - [15/Sep/2021:17:52:07 +0000] "GET http://localhost/health_check.php HTTP/1.1" 200 434 "-" "-" 0.017 - "18b43c5411b5c63b528e700104367c3d"
127.0.0.1 - - [15/Sep/2021:17:52:12 +0000] "GET http://localhost/health_check.php HTTP/1.1" 200 434 "-" "-" 0.017 - "45a123be32e42e190198a0297a9b566f"
127.0.0.1 - - [15/Sep/2021:17:52:17 +0000] "GET http://localhost/health_check.php HTTP/1.1" 200 434 "-" "-" 0.017 - "8b8e69110a367967460614db6edb7e42"

why I can not reach the website thank you.

**Comment by magenx** [comment]
if you run http it will work out of the box
if you need to run https, the you have to change nginx config, uncomment https variables

we run this script like every week, and it work without any issues

**Comment by mucan54** [comment]
I tried both but couldn't get response, does it can be about my system
CPU 3
RAM 4 GB
SSD 80 GB

**Comment by magenx** [comment]
there is no error in your message,
what exactly not working or any error you have?

**Comment by mucan54** [comment]
I added custom domain rather then server's ip address, and when I try to reach via domain I can not access, server doesnt respond, and in the logs of nginx access.log file I get this:

127.0.0.1 - - [15/Sep/2021:17:52:07 +0000] "GET http://localhost/health_check.php HTTP/1.1" 200 434 "-" "-" 0.017 - "18b43c5411b5c63b528e700104367c3d"
127.0.0.1 - - [15/Sep/2021:17:52:12 +0000] "GET http://localhost/health_check.php HTTP/1.1" 200 434 "-" "-" 0.017 - "45a123be32e42e190198a0297a9b566f"
127.0.0.1 - - [15/Sep/2021:17:52:17 +0000] "GET http://localhost/health_check.php HTTP/1.1" 200 434 "-" "-" 0.017 - "8b8e69110a367967460614db6edb7e42"

**Comment by mucan54** [comment]
I installed again with server default ip address I could access the site, what configurations are required when new domain added.

**Comment by magenx** [comment]
you must have DNS configured, domain name in nginx confg, and store base url

**Comment by mucan54** [comment]
I configured but now my assets doesn't loads from https, I can reach my website via https but in webpage all assests loads from http. As I understant magento can't detect https enabled.

**Comment by magenx** [comment]
you must have ssl certificate, base_url starts with https, for unsecure url too.
