### ISSUE TITLE
Typo should be lz4

### ISSUE THREAD

**Issue by jorgb90** [magenx/Magento-2-server-installation#53]
https://github.com/magenx/Magento-2-server-installation/blob/7b2e9e0f13acb1b20343efe4e0dd79818e4c3309/magenx.install.8.sh#L1699

**Comment by magenx** [comment]
that combination `lz4` vs `l4z` for `session` and `cache` compression was taken from magento 2 cli redis cache documentation and from https://github.com/colinmollenhour/Cm_Cache_Backend_Redis

you can see it like:

```
bin/magento setup:config:set --cache-backend-redis-compression-lib  --help | grep l4z
      --cache-backend-redis-compression-lib=CACHE-BACKEND-REDIS-COMPRESSION-LIB
Compression lib to use [snappy,lzf,l4z,zstd,gzip] (leave blank to determine automatically)
      --page-cache-redis-compression-lib=PAGE-CACHE-REDIS-COMPRESSION-LIB
Compression library to use [snappy,lzf,l4z,zstd,gzip] (leave blank to determine automatically)
```
