### ISSUE TITLE
Could not connect to the Amqp Server. install fails

### ISSUE THREAD

**Issue by rydemods** [magenx/Magento-2-server-installation#55]
Could not connect to the Amqp Server.

In InstallCommand.php line 274:

  Parameter validation failed

even tho rabitmq is running 
Listeners

Interface: [::], port: 25672, protocol: clustering, purpose: inter-node and CLI tool communication
Interface: 127.0.0.1, port: 5672, protocol: amqp, purpose: AMQP 0-9-1 and AMQP 1.0

ubuntu 20, ARM

**Comment by magenx** [comment]
on test instance there are no issues with rabbitmq

**Comment by rydemods** [comment]
Ive tested 5 times on new aws instances
Every time install fails I suggest you try for yourself.

**Comment by magenx** [comment]
could you please add some rabbitmq log lines , to see the reason for connection failed
you can tail it
or even magento debug log

**Comment by rydemods** [comment]
gave up now, delete the instance, don't have time to waste.. if you try
yourself you will see.

**Comment by magenx** [comment]
but you must have some little devops experience to manage it,
or at least to help you i need to see your error.

**Comment by corpsysgit** [comment]
LOG:

Failed to add user 'magento': the user already exists
 Successfully set permissions for 'magento' in virtual host '/' to '.*', '.*', '.*'
accepting AMQP connection <0.593.0> (127.0.0.1:53200 -> 127.0.0.1:5672)
Error on AMQP connection <0.593.0> (127.0.0.1:53200 -> 127.0.0.1:5672, state: starting):
AMQPLAIN login refused: user 'magento' - invalid credentials
closing AMQP connection <0.593.0> (127.0.0.1:53200 -> 127.0.0.1:5672)

**Comment by magenx** [comment]
you can delete user, and add it again with password from env.php
