### ISSUE TITLE
2Fa was installed with user admin

### ISSUE THREAD

**Issue by ilevennet** [magenx/Magento-2-server-installation#56]
During installation I've changed admin username with my own but at 2Fa configuration the script use "admin"

See this:
https://github.com/magenx/Magento-2-server-installation/blob/dd22866f30f2ff351df439fcc02db8d72dacd4a9/magenx.install.8.sh#L1777

**Comment by magenx** [comment]
this is now updated
thank you

**Comment by ilevennet** [comment]
Top!
