### ISSUE TITLE
Error on install screen "SERVICE 5672 OFFLINE"

### ISSUE THREAD

**Issue by musabatas** [magenx/Magento-2-server-installation#57]
I have added the following line to /etc/rabbitmq/rabbitmq-env.conf file and it was successfully connected.

`NODENAME=rabbit@localhost`

But, now i am getting "Could not connect to the Amqp Server." error.

**Comment by magenx** [comment]
rabbitmq configurtion is now updated
you will have to run: `bin/magento setup:upgrade --keep-generated`
to recreate your queue

https://github.com/magenx/Magento-2-server-installation/commit/9834c23c3830a2a337f5570d430d4e2ba1e4430d
