### ISSUE TITLE
Not working cacheflush

### ISSUE THREAD

**Issue by hiuryanderson** [magenx/Magento-2-server-installation#58]
By executing the command below:

/usr/local/bin/cacheflush

nginx restarts and doesn't work again!

Settings:

AWS EC2
ARM
Ubuntu 20.04
Instace type: m6g.large

**Comment by magenx** [comment]
you need to run nginx config test
`nginx -t`

or add test in systemd service file

**Comment by hiuryanderson** [comment]
I ran the command as you explained, but still the same error occurred, see below:
root@m2:/home/ubuntu# nginx -t
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful

I found that the problem here on my server is the command below:
sudo /usr/bin/systemctl reload nginx.service

This one works correctly:
sudo /usr/bin/systemctl restart nginx.service

The problem is the long time to restart compared to reload.

**Comment by magenx** [comment]
lets change it to `restart`
