### ISSUE TITLE
Correct method of installing full magento

### ISSUE THREAD

**Issue by Stuart-1** [magenx/Magento-2-server-installation#59]
I'm trying to install the full version of Magento, i can remove the following

curl -sO ${MAGENX_MSI_REPO}composer_replace

##replace?
sed -i '/"conflict":/ {
r composer_replace
N
}' composer.json
##replace?

but not sure if this is the correct way.

**Comment by magenx** [comment]
to install full magento version, just remove `replace {...}` block in composer.json 
and run composer install

but install everything is a bad idea...

**Comment by Stuart-1** [comment]
Thank you
