### ISSUE TITLE
InvalidArgumentException with Magento Minimal

### ISSUE THREAD

**Issue by teodorpav** [magenx/Magento-2-server-installation#6]
Hi,
with version 1.8.240.0 on >magento step (Magento minimal) I receive an error:

[InvalidArgumentException]                                           
  Package is not installed: magento/project-community-edition-2.4.0.0

Thank you

**Comment by magenx** [comment]
it was easy to think about, but
magento is very hard to make to work the way you need it ....

**Comment by magenx** [comment]
it is fixed now,
but you need to know magento to be ready for some hidden dependencies
that can break some functions

magento such magento

**Comment by teodorpav** [comment]
Thank you
