### ISSUE TITLE
Installation error with rabbitmq

### ISSUE THREAD

**Issue by Stuart-1** [magenx/Magento-2-server-installation#60]
Running the script on clean Debian 11, rabbitmq installs but with the following errors:

Processing triggers for man-db (2.9.4-2) ...
rabbitmq-server set on hold.
Killed
Job for rabbitmq-server.service failed because the control process exited with error code.
See "systemctl status rabbitmq-server.service" and "journalctl -xe" for details.
Error: unable to perform an operation on node 'rabbit@localhost'. Please see diagnostics information and suggestions below.

Most common reasons for this are:

 * Target node is unreachable (e.g. due to hostname resolution, TCP connection or firewall issues)
 * CLI tool fails to authenticate with the server (e.g. due to CLI tool's Erlang cookie not matching that of the server)
 * Target node is not running

**Comment by magenx** [comment]
do you see rabbitmq and epmd running , ports open?
if its not running can you please paste error log from syslog or rabbitmq log?
to see exact error

**Comment by Stuart-1** [comment]
Please find the syslog

Jan 11 21:05:50 debian-32gb-nbg1-1 systemd[1]: Starting RabbitMQ broker...
Jan 11 21:05:50 debian-32gb-nbg1-1 rabbitmq-server[34351]: Configuring logger redirection
Jan 11 21:05:52 debian-32gb-nbg1-1 rabbitmq-server[34351]:   ##  ##      RabbitMQ 3.8.27
Jan 11 21:05:52 debian-32gb-nbg1-1 rabbitmq-server[34351]:   ##  ##
Jan 11 21:05:52 debian-32gb-nbg1-1 rabbitmq-server[34351]:   ##########  Copyright (c) 2007-2021 VMware, Inc. or its affiliates.
Jan 11 21:05:52 debian-32gb-nbg1-1 rabbitmq-server[34351]:   ######  ##
Jan 11 21:05:52 debian-32gb-nbg1-1 rabbitmq-server[34351]:   ##########  Licensed under the MPL 2.0. Website: https://rabbitmq.com
Jan 11 21:05:52 debian-32gb-nbg1-1 rabbitmq-server[34351]:   Erlang:      23.2.6 [emu]
Jan 11 21:05:52 debian-32gb-nbg1-1 rabbitmq-server[34351]:   TLS Library: OpenSSL - OpenSSL 1.1.1k  25 Mar 2021
Jan 11 21:05:52 debian-32gb-nbg1-1 rabbitmq-server[34351]:   Doc guides:  https://rabbitmq.com/documentation.html
Jan 11 21:05:52 debian-32gb-nbg1-1 rabbitmq-server[34351]:   Support:     https://rabbitmq.com/contact.html
Jan 11 21:05:52 debian-32gb-nbg1-1 rabbitmq-server[34351]:   Tutorials:   https://rabbitmq.com/getstarted.html
Jan 11 21:05:52 debian-32gb-nbg1-1 rabbitmq-server[34351]:   Monitoring:  https://rabbitmq.com/monitoring.html
Jan 11 21:05:52 debian-32gb-nbg1-1 rabbitmq-server[34351]:   Logs: ***@***.******@***.***>
Jan 11 21:05:52 debian-32gb-nbg1-1 rabbitmq-server[34351]:         ***@***.******@***.***_upgrade.log>
Jan 11 21:05:52 debian-32gb-nbg1-1 rabbitmq-server[34351]:   Config file(s): (none)
Jan 11 21:05:54 debian-32gb-nbg1-1 rabbitmq-server[34351]:   Starting broker... completed with 0 plugins.
Jan 11 21:05:54 debian-32gb-nbg1-1 systemd[1]: Started RabbitMQ broker.
Jan 11 21:05:55 debian-32gb-nbg1-1 systemd[1]: Reloading.
Jan 11 21:05:55 debian-32gb-nbg1-1 systemd[1]: /lib/systemd/system/clamav-freshclam.service:11: Standard output type syslog is obsolete, automatically updating to journal. Please update your unit file, and consider removing the setting altogether.
Jan 11 21:05:55 debian-32gb-nbg1-1 systemd[1]: epmd.service: Current command vanished from the unit file, execution of the command list won't be resumed.
Jan 11 21:05:55 debian-32gb-nbg1-1 systemd[1]: Stopping RabbitMQ broker...
Jan 11 21:05:55 debian-32gb-nbg1-1 rabbitmqctl[34649]: Error: unable to perform an operation on node ***@***.***'. Please see diagnostics information and suggestions below.
Jan 11 21:05:55 debian-32gb-nbg1-1 rabbitmqctl[34649]: Most common reasons for this are:
Jan 11 21:05:55 debian-32gb-nbg1-1 rabbitmqctl[34649]:  * Target node is unreachable (e.g. due to hostname resolution, TCP connection or firewall issues)
Jan 11 21:05:55 debian-32gb-nbg1-1 rabbitmqctl[34649]:  * CLI tool fails to authenticate with the server (e.g. due to CLI tool's Erlang cookie not matching that of the server)
Jan 11 21:05:55 debian-32gb-nbg1-1 rabbitmqctl[34649]:  * Target node is not running
Jan 11 21:05:55 debian-32gb-nbg1-1 rabbitmqctl[34649]: In addition to the diagnostics info below:
Jan 11 21:05:55 debian-32gb-nbg1-1 rabbitmqctl[34649]:  * See the CLI, clustering and networking guides on https://rabbitmq.com/documentation.html to learn more
Jan 11 21:05:55 debian-32gb-nbg1-1 rabbitmqctl[34649]:  * Consult server logs on node ***@***.***
Jan 11 21:05:55 debian-32gb-nbg1-1 rabbitmqctl[34649]:  * If target node is configured to use long node names, don't forget to use --longnames with CLI tools
Jan 11 21:05:55 debian-32gb-nbg1-1 rabbitmqctl[34649]: DIAGNOSTICS
Jan 11 21:05:55 debian-32gb-nbg1-1 rabbitmqctl[34649]: ===========
Jan 11 21:05:55 debian-32gb-nbg1-1 rabbitmqctl[34649]: attempted to contact: ***@***.***
Jan 11 21:05:55 debian-32gb-nbg1-1 rabbitmqctl[34649]: ***@***.***:
Jan 11 21:05:55 debian-32gb-nbg1-1 rabbitmqctl[34649]:   * connected to epmd (port 4369) on localhost
Jan 11 21:05:55 debian-32gb-nbg1-1 rabbitmqctl[34649]:   * epmd reports node 'rabbit' uses port 25672 for inter-node and CLI tool traffic
Jan 11 21:05:55 debian-32gb-nbg1-1 rabbitmqctl[34649]:   * TCP connection succeeded but Erlang distribution failed
Jan 11 21:05:55 debian-32gb-nbg1-1 rabbitmqctl[34649]:   * suggestion: check if the Erlang cookie is identical for all server nodes and CLI tools
Jan 11 21:05:55 debian-32gb-nbg1-1 rabbitmqctl[34649]:   * suggestion: check if all server nodes and CLI tools use consistent hostnames when addressing each other
Jan 11 21:05:55 debian-32gb-nbg1-1 rabbitmqctl[34649]:   * suggestion: check if inter-node connections may be configured to use TLS. If so, all nodes and CLI tools must do that
Jan 11 21:05:55 debian-32gb-nbg1-1 rabbitmqctl[34649]:    * suggestion: see the CLI, clustering and networking guides on https://rabbitmq.com/documentation.html to learn more
Jan 11 21:05:55 debian-32gb-nbg1-1 rabbitmqctl[34649]: Current node details:
Jan 11 21:05:55 debian-32gb-nbg1-1 rabbitmqctl[34649]:  * node name: ***@***.***'
Jan 11 21:05:55 debian-32gb-nbg1-1 rabbitmqctl[34649]:  * effective user's home directory: /var/lib/rabbitmq
Jan 11 21:05:55 debian-32gb-nbg1-1 rabbitmqctl[34649]:  * Erlang cookie hash: CixCLKwg7YEl9iZCyl+RJQ==
Jan 11 21:06:00 debian-32gb-nbg1-1 systemd[1]: rabbitmq-server.service: Succeeded.
Jan 11 21:06:00 debian-32gb-nbg1-1 systemd[1]: Stopped RabbitMQ broker.
Jan 11 21:06:00 debian-32gb-nbg1-1 systemd[1]: rabbitmq-server.service: Consumed 11.106s CPU time.
Jan 11 21:06:00 debian-32gb-nbg1-1 epmd[34219]: epmd: Tue Jan 11 21:06:00 2022: got KILL_REQ - terminates normal
Jan 11 21:06:00 debian-32gb-nbg1-1 systemd[1]: epmd.service: Succeeded.
Jan 11 21:06:00 debian-32gb-nbg1-1 systemd[1]: Starting RabbitMQ broker...
Jan 11 21:06:00 debian-32gb-nbg1-1 rabbitmq-server[34718]: Configuring logger redirection
Jan 11 21:06:01 debian-32gb-nbg1-1 systemd[1]: Started Erlang Port Mapper Daemon.
Jan 11 21:06:01 debian-32gb-nbg1-1 systemd[1]: epmd.service: Succeeded.
Jan 11 21:06:01 debian-32gb-nbg1-1 systemd[1]: Started Erlang Port Mapper Daemon.
Jan 11 21:06:01 debian-32gb-nbg1-1 systemd[1]: epmd.service: Succeeded.
Jan 11 21:06:01 debian-32gb-nbg1-1 systemd[1]: Started Erlang Port Mapper Daemon.
Jan 11 21:06:01 debian-32gb-nbg1-1 systemd[1]: epmd.service: Succeeded.
Jan 11 21:06:01 debian-32gb-nbg1-1 systemd[1]: Started Erlang Port Mapper Daemon.
Jan 11 21:06:01 debian-32gb-nbg1-1 systemd[1]: epmd.service: Succeeded.
Jan 11 21:06:01 debian-32gb-nbg1-1 systemd[1]: Started Erlang Port Mapper Daemon.
Jan 11 21:06:01 debian-32gb-nbg1-1 systemd[1]: epmd.service: Succeeded.
Jan 11 21:06:01 debian-32gb-nbg1-1 systemd[1]: epmd.service: Start request repeated too quickly.
Jan 11 21:06:01 debian-32gb-nbg1-1 systemd[1]: epmd.service: Failed with result 'start-limit-hit'.
Jan 11 21:06:01 debian-32gb-nbg1-1 systemd[1]: Failed to start Erlang Port Mapper Daemon.
Jan 11 21:06:01 debian-32gb-nbg1-1 systemd[1]: epmd.socket: Failed with result 'service-start-limit-hit'.
Jan 11 21:06:01 debian-32gb-nbg1-1 rabbitmq-server[34718]: 21:06:01.551 [error]
Jan 11 21:06:01 debian-32gb-nbg1-1 rabbitmq-server[34718]: 21:06:01.551 [error] Supervisor net_sup had child net_kernel started with ***@***.***,shortnames], false, net_sup_dynamic) at undefined exit with reason {'EXIT',nodistribution} in context start_error
Jan 11 21:06:01 debian-32gb-nbg1-1 rabbitmq-server[34718]: 21:06:01.552 [error] CRASH REPORT Process <0.202.0> with 0 neighbours exited with reason: {error,badarg} in gen_server:init_it/6 line 401
Jan 11 21:06:01 debian-32gb-nbg1-1 rabbitmq-server[34718]: 21:06:01.554 [error] BOOT FAILED
Jan 11 21:06:01 debian-32gb-nbg1-1 rabbitmq-server[34718]: BOOT FAILED
Jan 11 21:06:01 debian-32gb-nbg1-1 rabbitmq-server[34718]: 21:06:01.554 [error] ===========
Jan 11 21:06:01 debian-32gb-nbg1-1 rabbitmq-server[34718]: ===========
Jan 11 21:06:01 debian-32gb-nbg1-1 rabbitmq-server[34718]: 21:06:01.554 [error] Exception during startup:
Jan 11 21:06:01 debian-32gb-nbg1-1 rabbitmq-server[34718]: Exception during startup:
Jan 11 21:06:01 debian-32gb-nbg1-1 rabbitmq-server[34718]: 21:06:01.554 [error]
Jan 11 21:06:01 debian-32gb-nbg1-1 rabbitmq-server[34718]: 21:06:01.554 [error]     supervisor:children_map/4 line 1171
Jan 11 21:06:01 debian-32gb-nbg1-1 rabbitmq-server[34718]:     supervisor:children_map/4 line 1171
Jan 11 21:06:01 debian-32gb-nbg1-1 rabbitmq-server[34718]: 21:06:01.554 [error]     supervisor:'-start_children/2-fun-0-'/3 line 355
Jan 11 21:06:01 debian-32gb-nbg1-1 rabbitmq-server[34718]:     supervisor:'-start_children/2-fun-0-'/3 line 355
Jan 11 21:06:01 debian-32gb-nbg1-1 rabbitmq-server[34718]: 21:06:01.554 [error]     supervisor:do_start_child/2 line 371
Jan 11 21:06:01 debian-32gb-nbg1-1 rabbitmq-server[34718]:     supervisor:do_start_child/2 line 371
Jan 11 21:06:01 debian-32gb-nbg1-1 rabbitmq-server[34718]: 21:06:01.554 [error]     supervisor:do_start_child_i/3 line 385
Jan 11 21:06:01 debian-32gb-nbg1-1 rabbitmq-server[34718]:     supervisor:do_start_child_i/3 line 385
Jan 11 21:06:01 debian-32gb-nbg1-1 rabbitmq-server[34718]: 21:06:01.554 [error]     rabbit_prelaunch:run_prelaunch_first_phase/0 line 27
Jan 11 21:06:01 debian-32gb-nbg1-1 rabbitmq-server[34718]:     rabbit_prelaunch:run_prelaunch_first_phase/0 line 27
Jan 11 21:06:01 debian-32gb-nbg1-1 rabbitmq-server[34718]: 21:06:01.554 [error]     rabbit_prelaunch:do_run/0 line 111
Jan 11 21:06:01 debian-32gb-nbg1-1 rabbitmq-server[34718]:     rabbit_prelaunch:do_run/0 line 111
Jan 11 21:06:01 debian-32gb-nbg1-1 rabbitmq-server[34718]: 21:06:01.555 [error]     rabbit_prelaunch_dist:setup/1 line 15
Jan 11 21:06:01 debian-32gb-nbg1-1 rabbitmq-server[34718]:     rabbit_prelaunch_dist:setup/1 line 15
Jan 11 21:06:01 debian-32gb-nbg1-1 rabbitmq-server[34718]: 21:06:01.555 [error]     rabbit_prelaunch_dist:duplicate_node_check/1 line 51
Jan 11 21:06:01 debian-32gb-nbg1-1 rabbitmq-server[34718]:     rabbit_prelaunch_dist:duplicate_node_check/1 line 51
Jan 11 21:06:01 debian-32gb-nbg1-1 rabbitmq-server[34718]: 21:06:01.555 [error] error:{badmatch,
Jan 11 21:06:01 debian-32gb-nbg1-1 rabbitmq-server[34718]: error:{badmatch,
Jan 11 21:06:01 debian-32gb-nbg1-1 rabbitmq-server[34718]: 21:06:01.555 [error]           {error,
Jan 11 21:06:01 debian-32gb-nbg1-1 rabbitmq-server[34718]:           {error,
Jan 11 21:06:01 debian-32gb-nbg1-1 rabbitmq-server[34718]: 21:06:01.555 [error]               {{shutdown,
Jan 11 21:06:01 debian-32gb-nbg1-1 rabbitmq-server[34718]:               {{shutdown,
Jan 11 21:06:01 debian-32gb-nbg1-1 rabbitmq-server[34718]: 21:06:01.555 [error]                    {failed_to_start_child,net_kernel,{'EXIT',nodistribution}}},
Jan 11 21:06:01 debian-32gb-nbg1-1 rabbitmq-server[34718]:                    {failed_to_start_child,net_kernel,{'EXIT',nodistribution}}},
Jan 11 21:06:01 debian-32gb-nbg1-1 rabbitmq-server[34718]: 21:06:01.555 [error]                {child,undefined,net_sup_dynamic,
Jan 11 21:06:01 debian-32gb-nbg1-1 rabbitmq-server[34718]:                {child,undefined,net_sup_dynamic,
Jan 11 21:06:01 debian-32gb-nbg1-1 rabbitmq-server[34718]: 21:06:01.555 [error]                    {erl_distribution,start_link,
Jan 11 21:06:01 debian-32gb-nbg1-1 rabbitmq-server[34718]:                    {erl_distribution,start_link,
Jan 11 21:06:01 debian-32gb-nbg1-1 rabbitmq-server[34718]: 21:06:01.555 [error]                        ***@***.***,shortnames],
Jan 11 21:06:01 debian-32gb-nbg1-1 rabbitmq-server[34718]:                        ***@***.***,shortnames],
Jan 11 21:06:01 debian-32gb-nbg1-1 rabbitmq-server[34718]: 21:06:01.555 [error]                         false,net_sup_dynamic]},
Jan 11 21:06:01 debian-32gb-nbg1-1 rabbitmq-server[34718]:                         false,net_sup_dynamic]},
Jan 11 21:06:01 debian-32gb-nbg1-1 rabbitmq-server[34718]: 21:06:01.555 [error]                    permanent,1000,supervisor,
Jan 11 21:06:01 debian-32gb-nbg1-1 rabbitmq-server[34718]:                    permanent,1000,supervisor,
Jan 11 21:06:01 debian-32gb-nbg1-1 rabbitmq-server[34718]: 21:06:01.555 [error]                    [erl_distribution]}}}}
Jan 11 21:06:01 debian-32gb-nbg1-1 rabbitmq-server[34718]:                    [erl_distribution]}}}}
Jan 11 21:06:01 debian-32gb-nbg1-1 rabbitmq-server[34718]: 21:06:01.555 [error]
Jan 11 21:06:02 debian-32gb-nbg1-1 rabbitmq-server[34718]: 21:06:02.556 [error] Supervisor rabbit_prelaunch_sup had child prelaunch started with rabbit_prelaunch:run_prelaunch_first_phase() at undefined exit with reason ***@***.***,shortnames],false,net_sup_dynamic]},permanent,1000,supervisor,[erl_distribution]}}}} in context start_error
Jan 11 21:06:02 debian-32gb-nbg1-1 rabbitmq-server[34718]: 21:06:02.556 [error] CRASH REPORT Process <0.152.0> with 0 neighbours exited with reason: ***@***.***,shortnames],false,net_sup_dynamic]},permanent,1000,supervisor,[erl_distribution]}}}}}},{rabbit_prelaunch_app,start,[normal,[]]}} in application_master:init/4 line 138
Jan 11 21:06:04 debian-32gb-nbg1-1 rabbitmq-server[34718]: {"Kernel pid ***@***.***,shortnames],false,net_sup_dynamic]},permanent,1000,supervisor,[erl_distribution]}}}}}},{rabbit_prelaunch_app,start,[normal,[]]}}}"}
Jan 11 21:06:04 debian-32gb-nbg1-1 rabbitmq-server[34718]: Kernel pid terminated (application_controller) ({application_start_failure,rabbitmq_prelaunch,{{shutdown,{failed_to_start_child,prelaunch,{badmatch,{error,{{shutdown,{failed_to_start_child,net_kernel,
Jan 11 21:06:04 debian-32gb-nbg1-1 rabbitmq-server[34718]: #015
Jan 11 21:06:04 debian-32gb-nbg1-1 rabbitmq-server[34718]: Crash dump is being written to: erl_crash.dump...done

**Comment by Stuart-1** [comment]
I think it's due to the Erlang Port Mapper Daemon Activation Socket

**Comment by Stuart-1** [comment]
I managed to resolve it by removing the following as it seems to already be duplicated in /usr/lib/systemd/system

cat > /etc/systemd/system/epmd.service <<END
[Unit]
Description=Erlang Port Mapper Daemon
After=network.target
Requires=epmd.socket

[Service]
ExecStart=/usr/bin/epmd -address 127.0.0.1 -daemon
Type=simple
StandardOutput=journal
StandardError=journal
User=epmd
Group=epmd

[Install]
Also=epmd.socket
WantedBy=multi-user.target
END

cat > /etc/systemd/system/epmd.socket <<END
[Unit]
Description=Erlang Port Mapper Daemon Activation Socket

[Socket]
ListenStream=4369
BindIPv6Only=both
Accept=no

[Install]
WantedBy=sockets.target
END

**Comment by magenx** [comment]
no its not duplicate
see the diffrence

**Comment by Stuart-1** [comment]
The new /etc/systemd/system/epmd.service & /etc/systemd/system/epmd.socket won't seem to run as they are currently running from /usr/lib/systemd/system

**Comment by Stuart-1** [comment]
When Rabbitmq starts on boot it automatically starts epmd, this then causes epmd.socket from etc/system/systemd to fail as the port is in use. If i shut everything down and start epmd.service first it runs ok but then rabbitmq fails as it also tries to run its own epmd.

**Comment by magenx** [comment]
there is only one service starts, with overrides in /etc/, default for all os configured,
you dont have to start epmd, only
`systemctl start rabbitmq-server`
