### ISSUE TITLE
Login backend 2FA 

### ISSUE THREAD

**Issue by HRR1337** [magenx/Magento-2-server-installation#62]
Hi there!

After installation of Magento there is an 'token' for g2fa to add to the authenticator. Have added it to my app manually. It's an correct one (without the last ======). 

Question; how can I login now with that 2fa on my backend? When I login with login and pass it says that they sent me an e-mail..

Thanks,

HRR

**Comment by magenx** [comment]
you just login with 2fa, it is already configured

**Comment by HRR1337** [comment]
When I go the firsttime to the admin, i need to fill in login and pass. Then i get a message that an email is sent. Thats all..

**Comment by jorgb90** [comment]
It shouldn't ask for your email to set 2FA when its already set, so don't know why its doing that, but you can either install a SMTP plugin to receive the e-mail or just disable 2FA with "bin/magento module:disable Magento_TwoFactorAuth" and login.
