### ISSUE TITLE
Permissions Media / Var Directories

### ISSUE THREAD

**Issue by jorgb90** [magenx/Magento-2-server-installation#64]
Hi,

It seems files in the pub/media and var dir get different user:group set shouldn't this be the same for all files and folders? Two different variants are there:

php-xxxx:php-xxxx
xxxx:php-xxxx

I think the last one is correct?

**Comment by jorgb90** [comment]
Found this cause the media dir is giving problems for us in the Media Gallery, some images won't open in preview window and the request gets a 500 error. Which is resulting in the following php error:

`[23-Feb-2022 08:53:48 UTC] PHP Fatal error:  Uncaught RuntimeException: ObjectManager isn't initialized in /home/xxxx/public_html/vendor/magento/framework/App/ObjectManager.php:36
Stack trace:
#0 /home/xxxx/public_html/vendor/magento/framework/File/Mime.php(84): Magento\Framework\App\ObjectManager::getInstance()
#1 /home/xxxx/public_html/pub/get.php(61): Magento\Framework\File\Mime->__construct()
#2 {main}
  thrown in /home/xxxx/public_html/vendor/magento/framework/App/ObjectManager.php on line 36`

**Comment by magenx** [comment]
could you please share magento version and media folder tree

**Comment by jorgb90** [comment]
Version 2.4.3-p1 with all applied patches. I just send you an e-mail as well.

**Comment by magenx** [comment]
yes, some files dont have permissions for nginx
https://github.com/magenx/Magento-2-server-installation/blob/f6ac9691e8ce9979dde45d3a1c4af2656eddfead/magenx.install.latest.sh#L1115

**Comment by musabatas** [comment]
I also have the same problem.

Product images side work well but when I tried to add an image from the WYSIWYG editor these images gives 500 errors.
After giving php-xxxx:php-xxxx and 2755 permissions these images showing up in frontend.

**Comment by Stuart-1** [comment]
I have the same issue, even after running setfacl -R -m u:nginx:r-X,g:nginx:r-X,d:u:nginx:r-X ${MAGENTO_WEB_ROOT_PATH} 

All files are under u:${MAGENTO_OWNER} g:${MAGENTO_PHP_USER}

**Comment by Stuart-1** [comment]
Media files are missing ACL's if they are uploaded through Magento admin

**Comment by Stuart-1** [comment]
I've tried "After giving php-xxxx:php-xxxx and 2755 permissions these images showing up in frontend." but still receive 500 error, the only way i can get the image to load is to apply setfacl as it's not inheriting this when adding images through magento wysiwyg. I'm not sure why it's not inheriting these values automatically.

**Comment by magenx** [comment]
yes ,there are bug / typo with permissions,
need to re-run test to find proper fix

**Comment by Stuart-1** [comment]
Thanks for the update, media files are now working fine for me.

**Comment by Gregory-Hepicloud** [comment]
We have same issue fresh install but on upload image is go to media folder but is not working on admin and front

![image](https://user-images.githubusercontent.com/4592618/156186691-53272db3-fc64-4cfa-92d8-bad1c1c3ad65.png)

![image](https://user-images.githubusercontent.com/4592618/156186822-684e0e40-3bad-48cc-b360-2fa88de25d89.png)

thx for helping

**Comment by magenx** [comment]
you need to make sure you have correct acl
var/tmp folder with php-fpm tmp directory pointed there

thank you

**Comment by Stuart-1** [comment]
I'm noticing there are now permission errors when in developer mode:

[2022-03-02 22:38:47] main.DEBUG: Can't create directory /home/public_html/generated/code/Magento/Framework/App/ResourceConnection/.
Class Magento\Framework\App\ResourceConnection\Proxy generation error: The requested class did not generate properly, because the 'generated' directory permission is read-only

And also when in production mode:

 main.CRITICAL: Directory "/home/public_html/pub/static/_cache" cannot be created Warning!mkdir(): Permission denied

I have applied the latest permissions fixes from the last commits.

**Comment by Stuart-1** [comment]
Thank you, for now i changed line 1149

From: setfacl -R -m u:${MAGENTO_OWNER}:rwx,g:${MAGENTO_PHP_USER}:rwx,o::-,d:u:${MAGENTO_OWNER}:rwx,d:g:${MAGENTO_PHP_USER}:rwx,d:o::- var pub/media

To: setfacl -R -m u:${MAGENTO_OWNER}:rwX,g:${MAGENTO_PHP_USER}:rwX,o::-,d:u:${MAGENTO_OWNER}:rwX,d:g:${MAGENTO_PHP_USER}:rwX,d:o::- generated var pub/media pub/static

This has solved the static/_cache and the 'generated' directory errors

**Comment by jorgb90** [comment]
I still have problems that uploaded media through admin has wrong permissions? Not clear to me how to fix this?

**Comment by Gregory-Hepicloud** [comment]
we have try but all time my uploaded image is wrong permission magento is so hard to make works 😓

**Comment by magenx** [comment]
when i try with this change https://github.com/magenx/Magento-2-server-installation/commit/63b3b424df268fe68523dcfcd5a250689d8036b1
there is no error on image

**Comment by jorgb90** [comment]
uploaded product images when creating products are triggering this permissions problem.

**Comment by magenx** [comment]
when app moves or uploads files it will break ACLs , because it will use system default tmp directory, it doesn't have any acls set

commit changes work this way,
you create tmp folder in var, so it will have proper ACL and permimssion,
and add tmp directory to php-fpm config.

when app moves or uploads files now, it will use our tmp folder with proper ACL inheritance

**Comment by jorgb90** [comment]
@magenx Yes. 63b3b42 did solve it, somehow the php reload didn't do its job.

**Comment by musabatas** [comment]
In fresh install, uploaded images responded 500 Error. Then I run `setfacl -R -m u:nginx:r-X,g:nginx:r-X,d:u:nginx:r-X pub/media` and than `bin/magento c:f` and now it looks working.

**Comment by hiuryanderson** [comment]
> when i try with this change [63b3b42](https://github.com/magenx/Magento-2-server-installation/commit/63b3b424df268fe68523dcfcd5a250689d8036b1) there is no error on image

I applied this change and it worked correctly on the backend and it is sending the images correctly.

However, in the customized product options, when you need to upload a file, the following message is displayed when adding the product to the cart with an image or any file:

PATH "/HOME/MYWEBSITETEST/PUBLIC_HTML/VAR/TMP/PHPL6HHPG" CANNOT BE USED WITH DIRECTORY "/TMP/"****

And when I remove the "php_admin_value[upload_tmp_dir]" option from php-fpm the product works but the backend upload doesn't work.

**Comment by magenx** [comment]
this is now fixed 
by defining the user's temporary directory correctly.

**Comment by hiuryanderson** [comment]
Working for me!
Thanks.
