### ISSUE TITLE
TwoFactorAuth not sending email

### ISSUE THREAD

**Issue by gfxguru** [magenx/Magento-2-server-installation#69]
browsing to admin url, twofactorauth not sending email to receive link to login. Email configured is working.

**Comment by Stuart-1** [comment]
I had to disable the twofactorauth and then enter the correct email address in Magento, i think it defaults to owner@example.com which was getting rejected by the email server, then re-enable twofactorauth and it should work. You can check the server logs as it will show if it's being rejected.

**Comment by magenx** [comment]
two issues now fixed
admin email is now configured for magento contacts
twofactor auth is actually preconfigured in cli, and you have two options,
disable module or use authenticator and enter code to login
