### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by bilalinamdar** [magenx/Magento-2-server-installation#7]
Dear Magenx
My config
CPU - 8
RAM - 8
DISK - 150 SSD

I really tried your script 3-4 time for like 5-6hr each time. Multiple time rebuild the VM. Below is the issue.

Everything work till the config.
But when the config comes it goes down hill.

**certbot-auto certonly --agree-tos --no-eff-email --email ${MAGE_ADMIN_EMAIL} --webroot -w ${MAGE_WEB_ROOT_PATH}/pub/**

It doesn't work. **Some challenges have failed error in certbot.**
It fails because it points to **/home/myshop/public_html/pub/** inplace it must point to **/usr/share/nginx/html**
certbot-auto certonly --agree-tos --no-eff-email --email  ${MAGE_ADMIN_EMAIL} --webroot -w /usr/share/nginx/html 

After crossing this step When everything is done. We get the issue of varnish on the frontpage
**503 backend fetch failed - guru meditation**

Now because of this issue it took be 3 attemp and lastly it was solved how i can't remember.

After that i got another issue. SSL is not working. So we need to change the config files manually and enable listen and ssl lines.

After that we got another issue even if somehow the page loads (LUMA) it doesn't work properly.
I mean CSS/JS files doesn't load properly. i tried deploy flush restart and everything but didn't work !

Finally gave up. Please if possible do check this.

**Comment by magenx** [comment]
docroot path is `/home/{username}/public_html/pub/`
varnish config is generated from magento, and you have to manually fix it to make it work, like probe path, etc,
nginx ssl will not work, again you need to manually enable it,

 CSS/JS part is easy to fix just need to read browser console messages, and magento logs

**Comment by bilalinamdar** [comment]
thx for quick reply !  👍
