### ISSUE TITLE
Unable to upload logo in admin

### ISSUE THREAD

**Issue by gfxguru** [magenx/Magento-2-server-installation#70]
The file was not uploaded. Is the error message when trying to add a logo from the Content/Design/Theme section. PHP error: Unknown: file created in the system's temporary directory in Unknown on line 0
File upload error - unable to create a temporary file in Unknown on line 0

**Comment by magenx** [comment]
make sure you have php-fpm config updated with :

```
php_admin_value[upload_tmp_dir] = "${MAGENTO_WEB_ROOT_PATH}/var/tmp"
php_admin_value[sys_temp_dir] = "${MAGENTO_WEB_ROOT_PATH}/var/tmp"
```

this will point to custom tmp directory in magento folder

**Comment by gfxguru** [comment]
are you referring to www.conf in the pool.d directory?

**Comment by magenx** [comment]
yes, this is variable, but
you need to use real path

**Comment by gfxguru** [comment]
the real path is already set to the correct location in the config file

**Comment by magenx** [comment]
yes, tmp folder must be there
