### ISSUE TITLE
enable SSL 

### ISSUE THREAD

**Issue by gfxguru** [magenx/Magento-2-server-installation#71]
I'm confused with enabling SSL for site. Your comments state you must have cert already, or if you know how to re-use certbot commands to re-issue, before we modify 
https://github.com/magenx/Magento-nginx-config/blob/master/magento2/sites-available/magento2.conf
and 
https://github.com/magenx/Magento-nginx-config/blob/master/magento2/conf_m2/varnish_proxy.conf

wasn't certbot/letsencrypt installed during initial install? I don't see either in the apt list --installed. Does this need to be reinstalled?

**Comment by magenx** [comment]
certbot is installed, you just type `certbot` command to run either standalone or webroot
depends on your config
