### ISSUE TITLE
Error 503 Backend fetch failed

### ISSUE THREAD

**Issue by gfxguru** [magenx/Magento-2-server-installation#72]
Website error: Error 503 Backend fetch failed

**Comment by gfxguru** [comment]
there are no errors in system.log

**Comment by gfxguru** [comment]
2022/03/18 12:31:52 [crit] 833#833: *433 open() "/home/webroot/public_html/pub/health_check.php" failed (13: Permission denied), client: 127.0.0.1, server: domain.com, request: "GET /health_check.php HTTP/1.1", host: "localhost"

**Comment by gfxguru** [comment]
nginx error log

**Comment by gfxguru** [comment]
Any other idea on how do diagnose this issue?

**Comment by gfxguru** [comment]
I found this issue
https://github.com/magento/magento2/issues/23613
but that doesn't seem to fix the problem

**Comment by jorgb90** [comment]
@gfxguru Varnish is doing a health check and as it seems it's not able to do so and thats why the backend fails.

If you edit the current varnish config (/etc/varnish/default.vcl) and comment or remove this part:

    .probe = {
        .url = "/health_check.php";
        .timeout = 2s;
        .interval = 5s;
        .window = 10;
        .threshold = 5;
   }

and restart varnish the error will be gone, but its better to find out why varnish is not able to reach this file locally.

**Comment by gfxguru** [comment]
I've run into this issue again. This was from a complete restore from a known working linode. I've tried restarting varnish but same issue.

**Comment by magenx** [comment]
this probe absolutely useless
you can remove it

**Comment by gfxguru** [comment]
This is the error I'm getting from varnish. 

root@server:~# varnishlog -q 'RespStatus == 503' -g request
*   << Request  >> 327682
-   Begin          req 327681 rxreq
-   Timestamp      Start: 1648150436.188853 0.000000 0.000000
-   Timestamp      Req: 1648150436.188853 0.000000 0.000000
-   VCL_use        boot
-   ReqStart       127.0.0.1 9750 a0
-   ReqMethod      GET
-   ReqURL         /
-   ReqProtocol    HTTP/1.1
-   ReqHeader      X-Real-IP: myipaddress
-   ReqHeader      X-Forwarded-For: myipaddress
-   ReqHeader      X-Forwarded-Host: mydomain.com
-   ReqHeader      Host: mydomain.com
-   ReqHeader      X-Scheme: https
-   ReqHeader      X-Forwarded-Proto: https
-   ReqHeader      X-Forwarded-Port: 443
-   ReqHeader      X-Secure: on
-   ReqHeader      user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:98.0) Gecko/20100101 Firefox/98.0
-   ReqHeader      accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8
-   ReqHeader      accept-language: en-US,en;q=0.5
-   ReqHeader      upgrade-insecure-requests: 1
-   ReqHeader      sec-fetch-dest: document
-   ReqHeader      sec-fetch-mode: navigate
-   ReqHeader      sec-fetch-site: none
-   ReqHeader      sec-fetch-user: ?1
-   ReqHeader      cache-control: max-age=0
-   ReqHeader      cookie: redirect=1; testing=1; sid=1815d0780337134f6d2d28d1d3921ada
-   ReqUnset       X-Forwarded-For: myipaddress
-   ReqHeader      X-Forwarded-For: myipaddress, 127.0.0.1
-   VCL_call       RECV
-   ReqHeader      grace: none
-   ReqURL         /
-   VCL_return     hash
-   VCL_call       HASH
-   VCL_return     lookup
-   VCL_call       MISS
-   VCL_return     fetch
-   Link           bereq 327683 fetch
-   Timestamp      Fetch: 1648150436.189116 0.000262 0.000262
-   RespProtocol   HTTP/1.1
-   RespStatus     503
-   RespReason     Backend fetch failed
-   RespHeader     Date: Thu, 24 Mar 2022 19:33:56 GMT
-   RespHeader     Server: Varnish
-   RespHeader     content-type: text/html; charset=utf-8
-   RespHeader     Retry-After: 5
-   RespHeader     X-Varnish: 327682
-   RespHeader     Age: 0
-   RespHeader     Via: 1.1 varnish (Varnish/6.5)
-   VCL_call       DELIVER
-   RespUnset      Age: 0
-   RespHeader     Pragma: no-cache
-   RespHeader     Expires: -1
-   RespHeader     Cache-Control: no-store, no-cache, must-revalidate, max-age=0
-   RespUnset      Server: Varnish
-   RespUnset      X-Varnish: 327682
-   RespUnset      Via: 1.1 varnish (Varnish/6.5)
-   VCL_return     deliver
-   Timestamp      Process: 1648150436.189140 0.000286 0.000024
-   Filters
-   RespHeader     Content-Length: 283
-   RespHeader     Connection: keep-alive
-   Timestamp      Resp: 1648150436.189199 0.000345 0.000059
-   ReqAcct        651 0 651 269 283 552
-   End
**  << BeReq    >> 327683
--  Begin          bereq 327682 fetch
--  VCL_use        boot
--  Timestamp      Start: 1648150436.188975 0.000000 0.000000
--  BereqMethod    GET
--  BereqURL       /
--  BereqProtocol  HTTP/1.1
--  BereqHeader    X-Real-IP: myipaddress
--  BereqHeader    X-Forwarded-Host: mydomain.com
--  BereqHeader    Host: mydomain.com
--  BereqHeader    X-Scheme: https
--  BereqHeader    X-Forwarded-Proto: https
--  BereqHeader    X-Forwarded-Port: 443
--  BereqHeader    X-Secure: on
--  BereqHeader    user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:98.0) Gecko/20100101 Firefox/98.0
--  BereqHeader    accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8
--  BereqHeader    accept-language: en-US,en;q=0.5
--  BereqHeader    upgrade-insecure-requests: 1
--  BereqHeader    sec-fetch-dest: document
--  BereqHeader    sec-fetch-mode: navigate
--  BereqHeader    sec-fetch-site: none
--  BereqHeader    sec-fetch-user: ?1
--  BereqHeader    cookie: redirect=1; testing=1; sid=1815d0780337134f6d2d28d1d3921ada
--  BereqHeader    X-Forwarded-For: myipaddress, 127.0.0.1
--  BereqHeader    grace: none
--  BereqHeader    Accept-Encoding: gzip
--  BereqHeader    X-Varnish: 327683
--  VCL_call       BACKEND_FETCH
--  VCL_return     fetch
--  FetchError     backend default: unhealthy
--  Timestamp      Beresp: 1648150436.188996 0.000021 0.000021
--  Timestamp      Error: 1648150436.188998 0.000022 0.000001
--  BerespProtocol HTTP/1.1
--  BerespStatus   503
--  BerespReason   Backend fetch failed
--  BerespHeader   Date: Thu, 24 Mar 2022 19:33:56 GMT
--  BerespHeader   Server: Varnish
--  VCL_call       BACKEND_ERROR
--  BerespHeader   content-type: text/html; charset=utf-8
--  BerespHeader   Retry-After: 5
--  VCL_return     deliver
--  Storage        malloc Transient
--  Length         283
--  BereqAcct      0 0 0 0 0 0
--  End

**Comment by gfxguru** [comment]
If I try removing the probe I get an error from nginx 404

**Comment by Stuart-1** [comment]
I had a similar issue, it was because magento was not configured to accept ssl, might be worth checking if it's configured. You will have to do this through cli if your unable to access magento admin panel

**Comment by gfxguru** [comment]
Nginx error 2022/03/24 14:52:19 [crit] 960#960: *1 open() "/home/magenx/public_html/pub/health_check.php" failed (13: Permission denied), client: 127.0.0.1, server: domain.com, request: "GET /health_check.php HTTP/1.1", host: "localhost"

**Comment by gfxguru** [comment]
I have a feeling using Webmin to edit files is changing access rights when saving
