### ISSUE TITLE
Elastic search continues to error

### ISSUE THREAD

**Issue by faruqhunter** [magenx/Magento-2-server-installation#76]
I keep getting the following two errors whenever I try to bring doco up

magenx-elasticsearch exited with code 1

magenx-cron           | /bin/ash: can't create /home/magenx/public_html/var/log/magento.cron.log: nonexistent directory

**Comment by faruqhunter** [comment]
here is what happend when I bring it up:

![image](https://user-images.githubusercontent.com/60839674/160329467-dc4baecf-72cc-4538-93ff-f4903169232c.png)

**Comment by magenx** [comment]
there was something with elasticsearch password file permissions
