### ISSUE TITLE
Doubt: Wouldn't using Litespeed instead of Nginx improve performance even more?

### ISSUE THREAD

**Issue by corpsysgit** [magenx/Magento-2-server-installation#78]
Doubt: Wouldn't using Litespeed instead of Nginx improve performance even more?

**Comment by magenx** [comment]
webserver is a read-only proxy, nothing to improve here...
what exactly litespeed improves???

**Comment by corpsysgit** [comment]
See what they say on their website:

LiteMage Makes Magento 2
up to 4 Times Faster!

Magento 2 loads up faster with LiteSpeed Web Server + LiteMage than any other HTTP/2 server and cache solution!

**Comment by corpsysgit** [comment]
https://www.litespeedtech.com/benchmarks/litespeed-magento2-faster-nginx-http2

**Comment by corpsysgit** [comment]
https://lscache.io/

**Comment by themew** [comment]
We compared LiteSpeed ($10 a month for a license - not opensource) with Magenx with Varnish (all open source) and got 44ms ttfb with LiteSpeed and 47ms ttfb with Magenx.

**Comment by corpsysgit** [comment]
Little difference then for a paid plan, huh?

> We compared LiteSpeed ($10 a month for a license - not open source) with Magenx with Varnish (all open source) and got 44ms ttfb with LiteSpeed and 47ms ttfb with Magenx.

Little difference then for a paid plan, huh?

**Comment by corpsysgit** [comment]
@themew 

Little difference then for a paid plan, huh?

**Comment by corpsysgit** [comment]
And has anyone tried the cloudflare premium plan?

Is there any performance improvement?

**Comment by magenx** [comment]
in magento you need to optimize the code and test the underlying raw output speed
without cache it should be almost the same as cached
you only add cache to save resources and to better control scaling.

for small shop all this doesnt matter...
