### ISSUE TITLE
ElasticSearch Credentials

### ISSUE THREAD

**Issue by joemstar** [magenx/Magento-2-server-installation#8]
When you install MAgento it asks for the ElasticSearch credentials and port but they are not automatically populated. The default port of 9200 isn't populated and the username elastic and auto generated password are not either. If you didn't save these from the earlier step, this could trip you up.

**Comment by teodorpav** [comment]
Ye have them on the previous step where the passwords are changed.
usually the port is localhost or 127.0.0.1

**Comment by magenx** [comment]
ELK config in WIP list,

**Comment by magenx** [comment]
this is fixed now, ELK passwords recorded in /opt/magenx/elasticsearch
and variable replaced in password prompt
