### ISSUE TITLE
Blank page after logging into phpMyAdmin

### ISSUE THREAD

**Issue by JAG007** [magenx/Magento-2-server-installation#80]
After logging into phpMyAdmin as root I get a blank page.

**Comment by magenx** [comment]
could you please paste error log related to this issue
auto installation always have issues with phpmyadmin

**Comment by JonnieGee** [comment]
#0 /usr/share/phpmyadmin/libraries/classes/Dbi/DbiMysqli.php(199): mysqli->query()
#1 /usr/share/phpmyadmin/libraries/classes/DatabaseInterface.php(316): PhpMyAdmin\Dbi\DbiMysqli->realQuery()
#2 /usr/share/phpmyadmin/libraries/classes/DatabaseInterface.php(1869): PhpMyAdmin\DatabaseInterface->tryQuery()
#3 /usr/share/phpmyadmin/libraries/classes/Menu.php(573): PhpMyAdmin\DatabaseInterface->fetchResult()
#4 /usr/share/phpmyadmin/libraries/classes/Menu.php(107): PhpMyAdmin\Menu->_getServerTabs()
#5 /usr/share/phpmyadmin/libraries/classes/Menu.php(70): PhpMyAdmin\Menu->_getMenu()
#6 /usr/share/phpmyadmin/libraries/classes/Header.php(445): PhpMyAdmin\Menu->getDisplay()
#7 /usr/share/phpmyadmin/libraries/classes/Response.php(323): PhpMyAdmin\Header->getDisplay()
#8 /usr/share/phpmyadmin/libraries/classes/Response.php(336): PhpMyAdmi" while reading response header from upstream, client: 72.14.99.28, server: routesman.com, request: "GET /mysql_3vtOYe/index.php HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "routesman.com"
