### ISSUE TITLE
Configure MySQL database

### ISSUE THREAD

**Issue by artmouse** [magenx/Magento-2-server-installation#82]
Reindexing on MariaDB 10.4 takes more time compared to other MariaDB or MySQL versions. 
As a workaround, we suggest modifying the default MariaDB configuration and setting the following parameters:

optimizer_switch='rowid_filter=off'
optimizer_use_condition_selectivity = 1

https://devdocs.magento.com/cloud/project/services-mysql.html

https://experienceleague.adobe.com/docs/commerce-operations/performance-best-practices/configuration.html

**Comment by jorgb90** [comment]
Add it in /etc/mysql/mariadb.cnf ? When added you see performance improvement?

**Comment by artmouse** [comment]
> Add it in /etc/mysql/mariadb.cnf ? When added you see performance improvement?

![изображение](https://user-images.githubusercontent.com/527232/168752513-cff301fa-461c-4217-a5c7-7265a46138dd.png)

**Comment by magenx** [comment]
this setup for mariadb `10.5.12`

**Comment by artmouse** [comment]
> this setup for mariadb `10.5.12`

Magento 2 not supported Maria DB 10.5 and have problem with indexation.

![изображение](https://user-images.githubusercontent.com/527232/168767214-5c491315-7797-4ff7-8b6d-53a2f6a84bf3.png)


https://devdocs.magento.com/guides/v2.4/install-gde/system-requirements.html

**Comment by artmouse** [comment]
See app/etc/di.xml

![изображение](https://user-images.githubusercontent.com/527232/168768282-e9c00a5b-06ed-494f-8c91-6821c0e2504a.png)

**Comment by artbambou** [comment]
I am uing MariaDB 10.6 and I do not have any casualties so far (+10ke products, +50ke customers, +30ke orders) (see reessolutions/db-override)

**Comment by artmouse** [comment]
We put version 10.4 into production, or better Perkona.

**Comment by magenx** [comment]
magento devs hardcoded `10.4` because they have hardcoded environment in commerce cloud.
nothing wrong with database version for application.
that simple...

**Comment by magenx** [comment]
why we dont use percona anymore - they dont have support for arm64
