### ISSUE TITLE
Adding a custom theme

### ISSUE THREAD

**Issue by gfxguru** [magenx/Magento-2-server-installation#84]
Do I need to use the development staging as in the install.log

to copy folders for development use:
useradd -d /home/staging -s /bin/bash staging
useradd -M -s /sbin/nologin -d /home/staging php-staging
usermod -g php-staging staging
rsync -a /home/magenx/public_html /home/staging/
chown -R staging:php-staging /home/staging/public_html
chmod 711 /home/staging
chmod 2750 /home/staging/public_html
setfacl -R -m m:rx,u:staging:rwx,g:php-staging:r-x,o::-,d:u:staging:rwx,d:g:php-staging:r-x,d:o::- /home/staging/public_html
cd /home/staging/public_html
setfacl -R -m u:staging:rwx,g:php-staging:rwx,o::-,d:u:staging:rwx,d:g:php-staging:rwx,d:o::- generated var pub/media pub/static
setfacl -R -m u:nginx:r-x,d:u:nginx:r-x /home/staging/public_html

My theme requires me to create a folder under vendor directory and install through composer. I'm wondering if my issues are because I didn't use the development staging route suggested. Can you briefly explain the above staging suggestions for development use?

**Comment by magenx** [comment]
if you need staging 
then you can copy / clone your magento to another folder and create new vhost
