### ISSUE TITLE
phpMyAdmin blank page

### ISSUE THREAD

**Issue by musabatas** [magenx/Magento-2-server-installation#87]
after loggin in, phpMyAdmin shows database table 1 sec. then return blank screen.

[https://prnt.sc/c_uzc6A9-Gfq](https://prnt.sc/c_uzc6A9-Gfq)

**Comment by themew** [comment]
Seeing this as well.  @musabatas are you using an unsecure IP or a secure url?

**Comment by musabatas** [comment]
Using it with secure url 
> Seeing this as well. @musabatas are you using an unsecure IP or a secure url?

**Comment by magenx** [comment]
phpmyadmin configuration provided as is, it needs more debug,
the probelm that every version and repository works different.

**Comment by musabatas** [comment]
I tried it on Magento 2.4.3-p1 and PHP version 7.4 it works without any issue, so the issue may be about the PHP version.

**Comment by magenx** [comment]
lets try to use this way
[phpmyadmin with composer](../blob/master/magenx.install.latest.sh#L1614)

**Comment by musabatas** [comment]
> lets try to use this way [phpmyadmin with composer](../blob/master/magenx.install.latest.sh#L1614)

Yes, this way works.
