### ISSUE TITLE
Cannot access Kibana or Webmin

### ISSUE THREAD

**Issue by joemstar** [magenx/Magento-2-server-installation#9]
Webmin installed using port 17639. When I browse to my url using that port, nothing loads. additionally, if i browse to mydomain.com/status I cannot access kibana

**Comment by magenx** [comment]
you need to debug webmin issues, 
if there is no firewall and webmin is listening

about kibana, if you have custom proxy setup then you can point to kibana local port, as all ELK services must be on 127.0.0.1
