### ISSUE TITLE
php-fpm CPU usage 100% when click save on product, category etc

### ISSUE THREAD

**Issue by flaviub** [magenx/Magento-2-server-installation#93]
Hello,

We use magenx for a magento VPS with 6 CPU and 6GB ram with Ubuntu 20.04 with php version 8.1 and php-fpm 

In magento dashboard if we save anything (product, category etc), the save process take verry long and when we run "top" command on vps we see CPU usage 100% from php-fpm.

We try this with new installation, default theme and this problem persist.

How can we solve this? (if you need more information, please tell us an I will post it here)

**Comment by magenx** [comment]
if you have cache disabled this could be the problem,
but we need to see logs and traces to understand exact issue

**Comment by flaviub** [comment]
Hello,

Cache is enabled, also magento is in production mod.

Can you tell me wich logs do you need?

**Comment by flaviub** [comment]
Hello,

I attached here a printscreen with the load when save a product quantity modification and also a printscreen with strace.

If you think will be more eficient if I give you the acces to the server, please tell me where to send the login information.

Thank you!
<img width="807" alt="Screenshot 2022-08-01 at 13 04 53" src="https://user-images.githubusercontent.com/110176867/182125562-e188211c-28c6-4130-b1db-f87253acf206.png">
<img width="575" alt="Screenshot 2022-08-01 at 12 58 53" src="https://user-images.githubusercontent.com/110176867/182125566-1f3f3ec0-b210-43b9-aaaf-ecf4632d2d82.png">

**Comment by dsadas23** [comment]
Hello magenx team,

Can you please help us with this issue? We don't know why this is happening..
Can you give us some directions? If is more easy for you I can give you ssh access

Thank you!

**Comment by magenx** [comment]
send access details to 
`admin@magenx.com`

**Comment by flaviub** [comment]
Thank you, I sent the email.
