### ISSUE TITLE
Firewall blocking Magento sending email

### ISSUE THREAD

**Issue by gfxguru** [magenx/Magento-2-server-installation#95]
our Magento is configured to use Google's server for email and the firewall is blocking outbound email.  Server is trying to communicate with Google SMTP. I assume I need to open the ports for both IP4 and IP6? is that correct? TLS and/or SSL

**Comment by magenx** [comment]
you can see syslog or maillog for outbound connections
check if firewall blocking email ports

if you have installed `csf firewall` has options to create specific configuration for:
port
ip address
outbound/inbound connections

https://download.configserver.com/csf/readme.txt

thank you

**Comment by gfxguru** [comment]
Syslog notice.

Aug  4 08:40:01 server kernel: [335053.468091] Firewall: *TCP6OUT Blocked* IN= OUT=eth0 SRC=ip6address DST=ip6address LEN=80 TC=0 HOPLIMIT=64 FLOWLBL=398412 PROTO=TCP SPT=27252 DPT=465 WINDOW=43200 RES=0x00 SYN URGP=0 UID=1001 GID=1001
Aug  4 08:40:02 server kernel: [335054.477945] Firewall: *TCP6OUT Blocked* IN= OUT=eth0 SRC=ip6address DST=ip6address LEN=80 TC=0 HOPLIMIT=64 FLOWLBL=260043 PROTO=TCP SPT=27252 DPT=465 WINDOW=43200 RES=0x00 SYN URGP=0 UID=1001 GID=1001
Aug  4 08:40:02 server kernel: [335054.478160] Firewall: *TCP_OUT Blocked* IN= OUT=eth0 SRC=ipaddress DST=108.177.122.109 LEN=60 TOS=0x00 PREC=0x00 TTL=64 ID=49508 DF PROTO=TCP SPT=25190 DPT=465 WINDOW=42340 RES=0x00 SYN URGP=0 UID=1001 GID=1001
Aug  4 08:40:03 server kernel: [335055.501929] Firewall: *TCP_OUT Blocked* IN= OUT=eth0 SRC=ipaddress DST=108.177.122.109 LEN=60 TOS=0x00 PREC=0x00 TTL=64 ID=49509 DF PROTO=TCP SPT=25190 DPT=465 WINDOW=42340 RES=0x00 SYN URGP=0 UID=1001 GID=1001

How do I open port 465? and do I need to add ip address?

**Comment by gfxguru** [comment]
I figured it out. But email is still not being sent.

**Comment by gfxguru** [comment]
having an issue with default postfix config. think I've got things figured out

**Comment by jorgb90** [comment]
Just use an external service like sendinblue, sendgrid or mailgun, always better than running your own.
