### ISSUE TITLE
directory access issues for Magento making changes

### ISSUE THREAD

**Issue by gfxguru** [magenx/Magento-2-server-installation#96]
Getting errors while compiling under magento user.

2022-08-06T23:51:08.071673+00:00] main.CRITICAL: Can't create directory /home/magento/public_html/generated/code/Magento/Framework/App/ResourceConnection/.
Class Magento\Framework\App\ResourceConnection\Proxy generation error: The requested class did not generate properly, because the 'generated' directory permission is read-only. If --- after running the 'bin/magento setup:di:compile' CLI command when the 'generated' directory permission is set to write --- the requested class did not generate properly, then you must add the generated class object to the signature of the related construct method, only. [] []
[2022-08-06T23:51:08.072217+00:00] main.DEBUG: Can't create directory /home/magento/public_html/generated/code/Magento/Framework/App/ResourceConnection/.
Class Magento\Framework\App\ResourceConnection\Proxy generation error: The requested class did not generate properly, because the 'generated' directory permission is read-only. If --- after running the 'bin/magento setup:di:compile' CLI command when the 'generated' directory permission is set to write --- the requested class did not generate properly, then you must add the generated class object to the signature of the related construct method, only. {"exception":"[object] (RuntimeException(code: 0): Can't create directory /home/magento/public_html/generated/code/Magento/Framework/App/ResourceConnection/.
Class Magento\\Framework\\App\\ResourceConnection\\Proxy generation error: The requested class did not generate properly, because the 'generated' directory permission is read-only. If --- after running the 'bin/magento setup:di:compile' CLI command when the 'generated' directory permission is set to write --- the requested class did not generate properly, then you must add the generated class object to the signature of the related construct method, only. at /home/magento/public_html/vendor/magento/framework/Code/Generator.php:140)"} []

directory permissions?

**Comment by GzimSokoli** [comment]
Having the same issue.

**Comment by magenx** [comment]
you have to make sure that permissions are correct
defaul installation is productions mode , write disabled

if you change to developer mode, you must have some idea how permissions and acl works


thank you

**Comment by jorgb90** [comment]
There is even some helpful information in the installation log you received at the end.. If you don't want to use a separate staging then just use the permission commands on production to solve this.
