### ISSUE TITLE
Compile Error 

### ISSUE THREAD

**Issue by musabatas** [magenx/Magento-2-server-installation#97]
There is an error when running compile. 
 
 "Class "Magento\AdminAdobeIms\Service\ImsConfig" does not exist."

**Comment by magenx** [comment]
adobe services removed now,
you can remove it too, it should work then

```
        "magento/module-adobe-ims": "*",
        "magento/module-adobe-ims-api": "*",
        "magento/module-admin-adobe-ims": "*",
```

**Comment by musabatas** [comment]
When I install 2.4.5 it returns 503 Backend fetch failed, but with 2.4.3-p2 return 200 OK. 
How to debug and solve it?

**Comment by magenx** [comment]
check varnish log, and magento/php log
also restart varnish

**Comment by musabatas** [comment]
Tried restarting varnish, nginx and even server completely. 

Now found the following PHP fatal error:

`PHP Fatal error:  Uncaught TypeError: str_replace(): Argument #3 ($subject) must be of type array|string, bool given in vendor/magento/framework/Filesystem/DirectoryList.php:137
Stack trace:
#0 vendor/magento/framework/Filesystem/DirectoryList.php(137): str_replace()
#1 vendor/magento/framework/Filesystem/DirectoryList.php(117): Magento\Framework\Filesystem\DirectoryList->normalizePath()
#2 vendor/magento/framework/App/Filesystem/DirectoryList.php(193): Magento\Framework\Filesystem\DirectoryList->__construct()
#3 vendor/magento/framework/App/Bootstrap.php(172): Magento\Framework\App\Filesystem\DirectoryList->__construct()
#4 vendor/magento/framework/App/Bootstrap.php(139): Magento\Framework\App\Bootstrap::createFilesystemDirectoryList()
#5 app/bootstrap.php(45): Magento\Framework\App\Bootstrap::populateAutoloader()
#6 pub/health_check.php(18): require('...')
#7 {main}`

**Comment by gfxguru** [comment]
I got the same error. 

  Class "Magento\AdminAdobeIms\Service\ImsConfig" does not exist
  Class Magento\TwoFactorAuth\Observer\ControllerActionPredispatch\Interceptor generation error: The requ
  ested class did not generate properly, because the 'generated' directory permission is read-only. If --
  - after running the 'bin/magento setup:di:compile' CLI command when the 'generated' directory permissio
  n is set to write --- the requested class did not generate properly, then you must add the generated cl
  ass object to the signature of the related construct method, only.

do we just add:
        "magento/module-adobe-ims": "*",
        "magento/module-adobe-ims-api": "*",
        "magento/module-admin-adobe-ims": "*",
 to the composer.json?

**Comment by Amadeco** [comment]
It is an issue introduced in Magento 2.4.5 :
You can refer to : 
https://github.com/magento/magento2/issues/35962

**Comment by gfxguru** [comment]
How do we get around and what's the purpose of adobeims?

**Comment by corpsysgit** [comment]
Remove all Ims quotes from this file:
TwoFactorAuth/Observer/ControllerActionPredispatch.php

should compile.

**Comment by gfxguru** [comment]
What do you mean by Remove all Ims quotes?

**Comment by artmouse** [comment]
> 

Have you solved this problem?

**Comment by artmouse** [comment]
> Tried restarting varnish, nginx and even server completely.
> 
> Now found the following PHP fatal error:
> 
> `PHP Fatal error: Uncaught TypeError: str_replace(): Argument #3 ($subject) must be of type array|string, bool given in vendor/magento/framework/Filesystem/DirectoryList.php:137 Stack trace: #0 vendor/magento/framework/Filesystem/DirectoryList.php(137): str_replace() #1 vendor/magento/framework/Filesystem/DirectoryList.php(117): Magento\Framework\Filesystem\DirectoryList->normalizePath() #2 vendor/magento/framework/App/Filesystem/DirectoryList.php(193): Magento\Framework\Filesystem\DirectoryList->__construct() #3 vendor/magento/framework/App/Bootstrap.php(172): Magento\Framework\App\Filesystem\DirectoryList->__construct() #4 vendor/magento/framework/App/Bootstrap.php(139): Magento\Framework\App\Bootstrap::createFilesystemDirectoryList() #5 app/bootstrap.php(45): Magento\Framework\App\Bootstrap::populateAutoloader() #6 pub/health_check.php(18): require('...') #7 {main}`

Have you solved this problem?

**Comment by musabatas** [comment]
> > `PHP Fatal error: Uncaught TypeError: str_replace(): Argument #3 ($subject) must be of type array|string, bool given in vendor/magento/framework/Filesystem/DirectoryList.php:137 `
> 
> Have you solved this problem?

Unfortunately, I haven't look for the solution yet. 

For now, I am using m2 version 2.4.3-p2 with php 7.4 because of most of extensions not really work with php8.1

**Comment by magenx** [comment]
magento always change some modules and its dependency requirements.
so you need to adjust your composer config file for every new version
