### ISSUE TITLE
Repository instalation error - file not found cdrom/dists/focal/Release

### ISSUE THREAD

**Issue by davirs** [magenx/Magento-2-server-installation#98]
Hey! During installation I am getting this error and the installation is interrupted.
How to bypass it?

Thank you

`
  [?] Install PHP ? [y/n][n]:y

  PHP repository installation:

  [?] Enter required PHP version: 8.1

Get:1 file:/cdrom focal InRelease
Ign:1 file:/cdrom focal InRelease
Get:2 file:/cdrom focal Release
Err:2 file:/cdrom focal Release
  File not found - /cdrom/dists/focal/Release (2: No such file or directory)
Hit:3 https://artifacts.elastic.co/packages/7.x/apt stable InRelease
Hit:4 http://br.archive.ubuntu.com/ubuntu focal InRelease
Hit:5 http://br.archive.ubuntu.com/ubuntu focal-updates InRelease
Hit:6 http://br.archive.ubuntu.com/ubuntu focal-backports InRelease
Hit:7 http://br.archive.ubuntu.com/ubuntu focal-security InRelease
Hit:8 http://ppa.launchpad.net/chris-lea/redis-server/ubuntu focal InRelease
Hit:9 http://nginx.org/packages/mainline/ubuntu focal InRelease
Get:11 https://dlm.mariadb.com/repo/mariadb-server/10.5.16/repo/ubuntu focal InRelease [7,767 B]
Hit:10 https://downloads.mariadb.com/Tools/ubuntu focal InRelease
Hit:12 http://ppa.launchpad.net/ondrej/php/ubuntu focal InRelease
Get:13 https://dlm.mariadb.com/repo/maxscale/latest/apt focal InRelease [6,384 B]
Reading package lists... Done
N: Ignoring file 'mariadb.list.old_1' in directory '/etc/apt/sources.list.d/' as it has an invalid filename extension
E: The repository 'file:/cdrom focal Release' no longer has a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

  REPOSITORY INSTALLATION ERROR`

**Comment by davirs** [comment]
Sorry, only after posting here did I understand what the problem was.
Maybe help someone else:
`sudo nano /etc/apt/sources.list
`
comment "cdrom" line with # and save

You can close this issue! thank you for your great work

**Comment by Ryzen720** [comment]
almost 2024 and u are still saving people, thanks
